// Code generated by gsx; DO NOT EDIT.

package main

import (
	"context"
	"fmt"
	"io"

	"github.com/gsxhq/gsx"
	_gsxf0 "github.com/jackielii/structpages"
)

type index struct {
	product `route:"/product Product"`
	team    `route:"/team Team"`
	contact `route:"/contact Contact"`
	throw   `route:"/throw Throw"`
}
type product struct{}
type team struct{}
type contact struct{}
type throw struct{}

func (p index) Page() gsx.Node {
	return gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
		_gsxgw := gsx.W(_gsxw)
//line pages.gsx:18:32
		_gsxgw.Node(ctx, Layout(LayoutProps{Children: gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
			_gsxgw := gsx.W(_gsxw)
//line pages.gsx:18:40
			_gsxgw.Node(ctx, p.Main())
			return _gsxgw.Err()
		})}))
		return _gsxgw.Err()
	})
}

func (p index) Main() gsx.Node {
	return gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
		_gsxgw := gsx.W(_gsxw)
//line pages.gsx:20:2
		_gsxgw.S("<h1")
		_gsxgw.S(">")
		_gsxgw.S("Welcome to the Index Page")
		_gsxgw.S("</h1>")
//line pages.gsx:21:2
		_gsxgw.S("<p")
		_gsxgw.S(">")
		_gsxgw.S("Navigate to the product, team, or contact pages using the links below:")
		_gsxgw.S("</p>")
//line pages.gsx:22:3
		_gsxgw.S("<a")
		_gsxv0, _gsxerr := _gsxf0.URLFor(ctx, (throw{}))
		if _gsxerr != nil {
			return _gsxerr
		}
		_gsxgw.S(" hx-get=\"")
		_gsxgw.URL(string(_gsxv0))
		_gsxgw.S("\"")
		_gsxgw.S(" hx-target=\"#main\"")
		_gsxgw.S(">")
		_gsxgw.S("Throw (Err)")
		_gsxgw.S("</a>")
		return _gsxgw.Err()
	})
}

func (p product) Page() gsx.Node {
	return gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
		_gsxgw := gsx.W(_gsxw)
//line pages.gsx:25:32
		_gsxgw.Node(ctx, Layout(LayoutProps{Children: gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
			_gsxgw := gsx.W(_gsxw)
//line pages.gsx:25:40
			_gsxgw.Node(ctx, p.Main())
			return _gsxgw.Err()
		})}))
		return _gsxgw.Err()
	})
}

func (p product) Main() gsx.Node {
	return gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
		_gsxgw := gsx.W(_gsxw)
//line pages.gsx:27:2
		_gsxgw.S("<h1")
		_gsxgw.S(">")
		_gsxgw.S("Product Page")
		_gsxgw.S("</h1>")
//line pages.gsx:28:2
		_gsxgw.S("<p")
		_gsxgw.S(">")
		_gsxgw.S("This is the product page.")
		_gsxgw.S("</p>")
		return _gsxgw.Err()
	})
}

func (p team) Page() gsx.Node {
	return gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
		_gsxgw := gsx.W(_gsxw)
//line pages.gsx:31:29
		_gsxgw.Node(ctx, Layout(LayoutProps{Children: gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
			_gsxgw := gsx.W(_gsxw)
//line pages.gsx:31:37
			_gsxgw.Node(ctx, p.Main())
			return _gsxgw.Err()
		})}))
		return _gsxgw.Err()
	})
}

func (p team) Main() gsx.Node {
	return gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
		_gsxgw := gsx.W(_gsxw)
//line pages.gsx:33:2
		_gsxgw.S("<h1")
		_gsxgw.S(">")
		_gsxgw.S("Team Page")
		_gsxgw.S("</h1>")
//line pages.gsx:34:2
		_gsxgw.S("<p")
		_gsxgw.S(">")
		_gsxgw.S("This is the team page.")
		_gsxgw.S("</p>")
		return _gsxgw.Err()
	})
}

func (p contact) Page() gsx.Node {
	return gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
		_gsxgw := gsx.W(_gsxw)
//line pages.gsx:37:32
		_gsxgw.Node(ctx, Layout(LayoutProps{Children: gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
			_gsxgw := gsx.W(_gsxw)
//line pages.gsx:37:40
			_gsxgw.Node(ctx, p.Main())
			return _gsxgw.Err()
		})}))
		return _gsxgw.Err()
	})
}

func (p contact) Main() gsx.Node {
	return gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
		_gsxgw := gsx.W(_gsxw)
//line pages.gsx:39:2
		_gsxgw.S("<h1")
		_gsxgw.S(">")
		_gsxgw.S("Contact Page")
		_gsxgw.S("</h1>")
//line pages.gsx:40:2
		_gsxgw.S("<p")
		_gsxgw.S(">")
		_gsxgw.S("This is the contact page.")
		_gsxgw.S("</p>")
		return _gsxgw.Err()
	})
}

func errFunc() (string, error) { return "", fmt.Errorf("this is an error") }

func (p throw) Page() gsx.Node {
	return gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
		_gsxgw := gsx.W(_gsxw)
//line pages.gsx:44:30
		_gsxgw.S("<p")
		_gsxgw.S(">")
//line pages.gsx:44:33
		_gsxv1, _gsxerr := errFunc()
		if _gsxerr != nil {
			return _gsxerr
		}
		_gsxgw.Text(string(_gsxv1))
		_gsxgw.S("</p>")
		return _gsxgw.Err()
	})
}

type LayoutProps struct {
	Children gsx.Node
}

func Layout(_gsxp LayoutProps) gsx.Node {
	return gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
		children := _gsxp.Children
		_gsxgw := gsx.W(_gsxw)
		_gsxgw.S("<!DOCTYPE html>")
//line pages.gsx:49:2
		_gsxgw.S("<html")
		_gsxgw.S(" lang=\"en\"")
		_gsxgw.S(">")
//line pages.gsx:50:3
		_gsxgw.S("<head")
		_gsxgw.S(">")
//line pages.gsx:51:4
		_gsxgw.S("<link")
		_gsxgw.S(" rel=\"stylesheet\"")
		_gsxgw.S(" href=\"https://unpkg.com/missing.css@1.1.3\"")
		_gsxgw.S("/>")
//line pages.gsx:52:4
		_gsxgw.S("<script")
		_gsxgw.S(" src=\"https://unpkg.com/htmx.org@2.0.4\"")
		_gsxgw.S(">")
		_gsxgw.S("</script>")
//line pages.gsx:53:4
		_gsxgw.S("<title")
		_gsxgw.S(">")
		_gsxgw.S("HTMX Example")
		_gsxgw.S("</title>")
		_gsxgw.S("</head>")
//line pages.gsx:55:3
		_gsxgw.S("<body")
		_gsxgw.S(">")
//line pages.gsx:56:4
		_gsxgw.S("<header")
		_gsxgw.S(" class=\"navbar\"")
		_gsxgw.S(">")
//line pages.gsx:57:5
		_gsxgw.S("<nav")
		_gsxgw.S(">")
//line pages.gsx:58:6
		_gsxgw.S("<ul")
		_gsxgw.S(" role=\"list\"")
		_gsxgw.S(" hx-push-url=\"true\"")
		_gsxgw.S(" hx-target=\"#main\"")
		_gsxgw.S(">")
//line pages.gsx:59:7
		_gsxgw.S("<li")
		_gsxgw.S(">")
//line pages.gsx:59:11
		_gsxgw.S("<a")
		_gsxv2, _gsxerr := _gsxf0.URLFor(ctx, (index{}))
		if _gsxerr != nil {
			return _gsxerr
		}
		_gsxgw.S(" hx-get=\"")
		_gsxgw.URL(string(_gsxv2))
		_gsxgw.S("\"")
		_gsxgw.S(">")
		_gsxgw.S("Home")
		_gsxgw.S("</a>")
		_gsxgw.S("</li>")
//line pages.gsx:60:7
		_gsxgw.S("<li")
		_gsxgw.S(">")
//line pages.gsx:60:11
		_gsxgw.S("<a")
		_gsxv3, _gsxerr := _gsxf0.URLFor(ctx, (product{}))
		if _gsxerr != nil {
			return _gsxerr
		}
		_gsxgw.S(" hx-get=\"")
		_gsxgw.URL(string(_gsxv3))
		_gsxgw.S("\"")
		_gsxgw.S(">")
		_gsxgw.S("Product")
		_gsxgw.S("</a>")
		_gsxgw.S("</li>")
//line pages.gsx:61:7
		_gsxgw.S("<li")
		_gsxgw.S(">")
//line pages.gsx:61:11
		_gsxgw.S("<a")
		_gsxv4, _gsxerr := _gsxf0.URLFor(ctx, (team{}))
		if _gsxerr != nil {
			return _gsxerr
		}
		_gsxgw.S(" hx-get=\"")
		_gsxgw.URL(string(_gsxv4))
		_gsxgw.S("\"")
		_gsxgw.S(">")
		_gsxgw.S("Team")
		_gsxgw.S("</a>")
		_gsxgw.S("</li>")
//line pages.gsx:62:7
		_gsxgw.S("<li")
		_gsxgw.S(">")
//line pages.gsx:62:11
		_gsxgw.S("<a")
		_gsxv5, _gsxerr := _gsxf0.URLFor(ctx, (contact{}))
		if _gsxerr != nil {
			return _gsxerr
		}
		_gsxgw.S(" hx-get=\"")
		_gsxgw.URL(string(_gsxv5))
		_gsxgw.S("\"")
		_gsxgw.S(">")
		_gsxgw.S("Contact")
		_gsxgw.S("</a>")
		_gsxgw.S("</li>")
		_gsxgw.S("</ul>")
		_gsxgw.S("</nav>")
		_gsxgw.S("</header>")
//line pages.gsx:66:4
		_gsxgw.S("<main")
		_gsxgw.S(" id=\"main\"")
		_gsxgw.S(">")
//line pages.gsx:66:20
		_gsxgw.Node(ctx, children)
		_gsxgw.S("</main>")
		_gsxgw.S("</body>")
		_gsxgw.S("</html>")
		return _gsxgw.Err()
	})
}

type ErrorPageProps struct {
	Err error
}

func ErrorPage(_gsxp ErrorPageProps) gsx.Node {
	return gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
		err := _gsxp.Err
		_gsxgw := gsx.W(_gsxw)
//line pages.gsx:71:34
		_gsxgw.Node(ctx, Layout(LayoutProps{Children: gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
			_gsxgw := gsx.W(_gsxw)
//line pages.gsx:71:42
			_gsxgw.Node(ctx, ErrorComp(ErrorCompProps{Err: err}))
			return _gsxgw.Err()
		})}))
		return _gsxgw.Err()
	})
}

type ErrorCompProps struct {
	Err error
}

func ErrorComp(_gsxp ErrorCompProps) gsx.Node {
	return gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
		err := _gsxp.Err
		_gsxgw := gsx.W(_gsxw)
//line pages.gsx:74:2
		_gsxgw.S("<h1")
		_gsxgw.S(">")
		_gsxgw.S("Error")
		_gsxgw.S("</h1>")
//line pages.gsx:75:2
		_gsxgw.S("<p")
		_gsxgw.S(">")
//line pages.gsx:75:5
		_gsxgw.Text(string(err.Error()))
		_gsxgw.S("</p>")
		return _gsxgw.Err()
	})
}
