// Code generated by gsx; DO NOT EDIT.

package admin

import (
	"context"
	"io"
	"strconv"

	"github.com/gsxhq/gsx"
	"github.com/jackielii/structpages"
	"github.com/jackielii/structpages/examples/blog/store"
	"github.com/jackielii/structpages/examples/blog/ui/components"
)

// StatCell — capitalized (gsx components must be Capitalized; the templ name
// was lowercase `statCell`).

type StatCellProps struct {
	Label string
	Value int
	Attrs gsx.Attrs
}

func StatCell(_gsxp StatCellProps) gsx.Node {
	return gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
		label := _gsxp.Label
		value := _gsxp.Value
		_gsxgw := gsx.W(_gsxw)
//line components.gsx:16:2
		_gsxgw.S("<div")
		_gsxgw.S(" class=\"")
		_gsxgw.Class(gsx.Class("rounded-lg border bg-white p-4 text-center shadow-sm"), gsx.Class(_gsxp.Attrs.Class()))
		_gsxgw.S("\"")
		_gsxgw.StyleMerged("", _gsxp.Attrs.Style())
		_gsxgw.Spread(ctx, _gsxp.Attrs.Without("class", "style"))
		_gsxgw.S(">")
//line components.gsx:17:3
		_gsxgw.S("<div")
		_gsxgw.S(" class=\"text-3xl font-semibold text-slate-900\"")
		_gsxgw.S(">")
//line components.gsx:17:54
		_gsxgw.Text(strconv.FormatInt(int64(value), 10))
		_gsxgw.S("</div>")
//line components.gsx:18:3
		_gsxgw.S("<div")
		_gsxgw.S(" class=\"mt-1 text-xs uppercase tracking-wide text-slate-500\"")
		_gsxgw.S(">")
//line components.gsx:18:68
		_gsxgw.Text(string(label))
		_gsxgw.S("</div>")
		_gsxgw.S("</div>")
		return _gsxgw.Err()
	})
}

type StatsGridProps struct {
	Stats store.Stats
	Attrs gsx.Attrs
}

func StatsGrid(_gsxp StatsGridProps) gsx.Node {
	return gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
		stats := _gsxp.Stats
		_gsxgw := gsx.W(_gsxw)
//line components.gsx:23:2
		_gsxgw.S("<div")
		if !_gsxp.Attrs.Has("id") {
			_gsxv0, _gsxerr := structpages.ID(ctx, StatsGrid)
			if _gsxerr != nil {
				return _gsxerr
			}
			_gsxgw.S(" id=\"")
			_gsxgw.AttrValue(string(_gsxv0))
			_gsxgw.S("\"")
		}
		_gsxgw.S(" class=\"")
		_gsxgw.Class(gsx.Class("grid grid-cols-2 gap-3 md:grid-cols-4"), gsx.Class(_gsxp.Attrs.Class()))
		_gsxgw.S("\"")
		_gsxgw.StyleMerged("", _gsxp.Attrs.Style())
		_gsxgw.Spread(ctx, _gsxp.Attrs.Without("class", "style"))
		_gsxgw.S(">")
//line components.gsx:24:3
		_gsxgw.Node(ctx, StatCell(StatCellProps{Label: "Posts", Value: stats.Posts}))
//line components.gsx:25:3
		_gsxgw.Node(ctx, StatCell(StatCellProps{Label: "Drafts", Value: stats.Drafts}))
//line components.gsx:26:3
		_gsxgw.Node(ctx, StatCell(StatCellProps{Label: "Comments", Value: stats.Comments}))
//line components.gsx:27:3
		_gsxgw.Node(ctx, StatCell(StatCellProps{Label: "Categories", Value: stats.Categories}))
		_gsxgw.S("</div>")
		return _gsxgw.Err()
	})
}

type RecentPostsCardProps struct {
	Posts []store.Post
	Attrs gsx.Attrs
}

func RecentPostsCard(_gsxp RecentPostsCardProps) gsx.Node {
	return gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
		posts := _gsxp.Posts
		_gsxgw := gsx.W(_gsxw)
//line components.gsx:32:2
		_gsxgw.S("<div")
		if !_gsxp.Attrs.Has("id") {
			_gsxv1, _gsxerr := structpages.ID(ctx, RecentPostsCard)
			if _gsxerr != nil {
				return _gsxerr
			}
			_gsxgw.S(" id=\"")
			_gsxgw.AttrValue(string(_gsxv1))
			_gsxgw.S("\"")
		}
		_gsxgw.ClassMerged(_gsxp.Attrs.Class())
		_gsxgw.StyleMerged("", _gsxp.Attrs.Style())
		_gsxgw.Spread(ctx, _gsxp.Attrs.Without("class", "style"))
		_gsxgw.S(">")
//line components.gsx:33:3
		_gsxgw.Node(ctx, components.Card(components.CardProps{Title: "Recent posts", Children: gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
			_gsxgw := gsx.W(_gsxw)
//line components.gsx:34:4
			_gsxgw.S("<ul")
			_gsxgw.S(" class=\"divide-y text-sm\"")
			_gsxgw.S(">")
//line components.gsx:35:5
			if len(posts) == 0 {
//line components.gsx:36:6
				_gsxgw.S("<li")
				_gsxgw.S(" class=\"py-2 text-slate-500\"")
				_gsxgw.S(">")
				_gsxgw.S("No posts yet.")
				_gsxgw.S("</li>")
			}
//line components.gsx:38:5
			for _, p := range posts {
//line components.gsx:39:6
				_gsxgw.S("<li")
				_gsxgw.S(" class=\"flex items-center justify-between py-2\"")
				_gsxgw.S(">")
//line components.gsx:40:7
				_gsxgw.S("<a")
				_gsxgw.S(" class=\"hover:underline\"")
				_gsxv2, _gsxerr := components.URL(ctx, postEditPage{}, "id", p.ID)
				if _gsxerr != nil {
					return _gsxerr
				}
				_gsxgw.S(" href=\"")
				_gsxgw.URL(string(_gsxv2))
				_gsxgw.S("\"")
				_gsxgw.S(">")
//line components.gsx:41:8
				_gsxgw.Text(string(p.Title))
				_gsxgw.S("</a>")
//line components.gsx:43:7
				if p.Published {
//line components.gsx:44:8
					_gsxgw.S("<span")
					_gsxgw.S(" class=\"rounded bg-emerald-100 px-2 py-0.5 text-xs text-emerald-800\"")
					_gsxgw.S(">")
					_gsxgw.S("live")
					_gsxgw.S("</span>")
				} else {
//line components.gsx:46:8
					_gsxgw.S("<span")
					_gsxgw.S(" class=\"rounded bg-slate-200 px-2 py-0.5 text-xs text-slate-700\"")
					_gsxgw.S(">")
					_gsxgw.S("draft")
					_gsxgw.S("</span>")
				}
				_gsxgw.S("</li>")
			}
			_gsxgw.S("</ul>")
			return _gsxgw.Err()
		})}))
		_gsxgw.S("</div>")
		return _gsxgw.Err()
	})
}

type PostsTableProps struct {
	Posts []store.Post
	Attrs gsx.Attrs
}

func PostsTable(_gsxp PostsTableProps) gsx.Node {
	return gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
		posts := _gsxp.Posts
		_gsxgw := gsx.W(_gsxw)
//line components.gsx:56:2
		_gsxgw.S("<div")
		if !_gsxp.Attrs.Has("id") {
			_gsxv3, _gsxerr := structpages.ID(ctx, PostsTable)
			if _gsxerr != nil {
				return _gsxerr
			}
			_gsxgw.S(" id=\"")
			_gsxgw.AttrValue(string(_gsxv3))
			_gsxgw.S("\"")
		}
		_gsxgw.S(" class=\"")
		_gsxgw.Class(gsx.Class("overflow-hidden rounded-lg border bg-white shadow-sm"), gsx.Class(_gsxp.Attrs.Class()))
		_gsxgw.S("\"")
		_gsxgw.StyleMerged("", _gsxp.Attrs.Style())
		_gsxgw.Spread(ctx, _gsxp.Attrs.Without("class", "style"))
		_gsxgw.S(">")
//line components.gsx:57:3
		_gsxgw.S("<table")
		_gsxgw.S(" class=\"w-full text-sm\"")
		_gsxgw.S(">")
//line components.gsx:58:4
		_gsxgw.S("<thead")
		_gsxgw.S(" class=\"bg-slate-50 text-left text-xs uppercase tracking-wide text-slate-500\"")
		_gsxgw.S(">")
//line components.gsx:59:5
		_gsxgw.S("<tr")
		_gsxgw.S(">")
//line components.gsx:60:6
		_gsxgw.S("<th")
		_gsxgw.S(" class=\"px-3 py-2\"")
		_gsxgw.S(">")
		_gsxgw.S("Title")
		_gsxgw.S("</th>")
//line components.gsx:61:6
		_gsxgw.S("<th")
		_gsxgw.S(" class=\"px-3 py-2\"")
		_gsxgw.S(">")
		_gsxgw.S("Status")
		_gsxgw.S("</th>")
//line components.gsx:62:6
		_gsxgw.S("<th")
		_gsxgw.S(" class=\"px-3 py-2\"")
		_gsxgw.S(">")
		_gsxgw.S("Created")
		_gsxgw.S("</th>")
//line components.gsx:63:6
		_gsxgw.S("<th")
		_gsxgw.S(" class=\"px-3 py-2\"")
		_gsxgw.S(">")
		_gsxgw.S("</th>")
		_gsxgw.S("</tr>")
		_gsxgw.S("</thead>")
//line components.gsx:66:4
		_gsxgw.S("<tbody")
		_gsxgw.S(">")
//line components.gsx:67:5
		for _, p := range posts {
//line components.gsx:68:6
			_gsxgw.S("<tr")
			_gsxgw.S(" class=\"border-t\"")
			_gsxgw.S(">")
//line components.gsx:69:7
			_gsxgw.S("<td")
			_gsxgw.S(" class=\"px-3 py-2 font-medium\"")
			_gsxgw.S(">")
//line components.gsx:70:8
			_gsxgw.S("<a")
			_gsxgw.S(" class=\"hover:underline\"")
			_gsxv4, _gsxerr := components.URL(ctx, postEditPage{}, "id", p.ID)
			if _gsxerr != nil {
				return _gsxerr
			}
			_gsxgw.S(" href=\"")
			_gsxgw.URL(string(_gsxv4))
			_gsxgw.S("\"")
			_gsxgw.S(">")
//line components.gsx:70:92
			_gsxgw.Text(string(p.Title))
			_gsxgw.S("</a>")
			_gsxgw.S("</td>")
//line components.gsx:72:7
			_gsxgw.S("<td")
			_gsxgw.S(" class=\"px-3 py-2\"")
			_gsxgw.S(">")
//line components.gsx:73:8
			if p.Published {
//line components.gsx:74:9
				_gsxgw.S("<span")
				_gsxgw.S(" class=\"rounded bg-emerald-100 px-2 py-0.5 text-xs text-emerald-800\"")
				_gsxgw.S(">")
				_gsxgw.S("published")
				_gsxgw.S("</span>")
			} else {
//line components.gsx:76:9
				_gsxgw.S("<span")
				_gsxgw.S(" class=\"rounded bg-slate-200 px-2 py-0.5 text-xs text-slate-700\"")
				_gsxgw.S(">")
				_gsxgw.S("draft")
				_gsxgw.S("</span>")
			}
			_gsxgw.S("</td>")
//line components.gsx:79:7
			_gsxgw.S("<td")
			_gsxgw.S(" class=\"px-3 py-2 text-slate-500\"")
			_gsxgw.S(">")
//line components.gsx:79:44
			_gsxgw.Text(string(p.CreatedAt.Format("Jan 2, 2006")))
			_gsxgw.S("</td>")
//line components.gsx:80:7
			_gsxgw.S("<td")
			_gsxgw.S(" class=\"px-3 py-2 text-right\"")
			_gsxgw.S(">")
//line components.gsx:81:8
			_gsxgw.S("<form")
			_gsxgw.S(" method=\"POST\"")
			_gsxv5, _gsxerr := components.URL(ctx, postDeleteHandler{}, "id", p.ID)
			if _gsxerr != nil {
				return _gsxerr
			}
			_gsxgw.S(" action=\"")
			_gsxgw.URL(string(_gsxv5))
			_gsxgw.S("\"")
			_gsxv6, _gsxerr := structpages.URLFor(ctx, postDeleteHandler{}, "id", p.ID)
			if _gsxerr != nil {
				return _gsxerr
			}
			_gsxgw.S(" hx-post=\"")
			_gsxgw.URL(string(_gsxv6))
			_gsxgw.S("\"")
			_gsxv7, _gsxerr := structpages.IDTarget(ctx, PostsTable)
			if _gsxerr != nil {
				return _gsxerr
			}
			_gsxgw.S(" hx-target=\"")
			_gsxgw.AttrValue(string(_gsxv7))
			_gsxgw.S("\"")
			_gsxgw.S(" hx-swap=\"outerHTML\"")
			_gsxgw.S(" hx-confirm=\"Delete this post?\"")
			_gsxgw.S(" class=\"inline\"")
			_gsxgw.S(">")
//line components.gsx:90:9
			_gsxgw.S("<button")
			_gsxgw.S(" class=\"text-xs text-red-600 hover:underline\"")
			_gsxgw.S(" type=\"submit\"")
			_gsxgw.S(">")
			_gsxgw.S("Delete")
			_gsxgw.S("</button>")
			_gsxgw.S("</form>")
			_gsxgw.S("</td>")
			_gsxgw.S("</tr>")
		}
//line components.gsx:95:5
		if len(posts) == 0 {
//line components.gsx:96:6
			_gsxgw.S("<tr")
			_gsxgw.S(">")
//line components.gsx:96:10
			_gsxgw.S("<td")
			_gsxgw.S(" colspan=\"4\"")
			_gsxgw.S(" class=\"px-3 py-6 text-center text-slate-500\"")
			_gsxgw.S(">")
			_gsxgw.S("No posts yet.")
			_gsxgw.S("</td>")
			_gsxgw.S("</tr>")
		}
		_gsxgw.S("</tbody>")
		_gsxgw.S("</table>")
		_gsxgw.S("</div>")
		return _gsxgw.Err()
	})
}
