// Code generated by gsx; DO NOT EDIT.

package admin

import (
	"context"
	"io"
	"net/http"

	"github.com/gsxhq/gsx"
	"github.com/jackielii/structpages"
	"github.com/jackielii/structpages/examples/blog/auth"
	"github.com/jackielii/structpages/examples/blog/store"
	"github.com/jackielii/structpages/examples/blog/ui/components"
	"github.com/jackielii/structpages/examples/blog/ui/layout"
)

type dashboardPage struct{}

type dashboardProps struct {
	User        store.User
	Stats       store.Stats
	RecentPosts []store.Post
}

// Props demonstrates the Props + RenderTarget pattern. Each widget is a
// standalone gsx function (StatsGrid, RecentPostsCard) so HTMX refresh
// requests with HX-Target: #stats-grid or #recent-posts-card resolve here
// and only the touched data is loaded — no full page work.
//
// Returns dashboardProps directly — gsx now emits method components as
// func (p dashboardPage) Page(props dashboardProps) gsx.Node without a wrapper struct.
func (p dashboardPage) Props(r *http.Request, s *store.Store, target structpages.RenderTarget) (dashboardProps, error) {
	switch {
	case target.Is(StatsGrid):
		return dashboardProps{}, structpages.RenderComponent(StatsGrid(StatsGridProps{Stats: s.Stats()}))

	case target.Is(RecentPostsCard):
		posts, _ := s.ListPosts(store.PostFilter{IncludeDraft: true, PageSize: 5})
		return dashboardProps{}, structpages.RenderComponent(RecentPostsCard(RecentPostsCardProps{Posts: posts}))
	}

	user, _ := auth.UserFromContext(r.Context())
	posts, _ := s.ListPosts(store.PostFilter{IncludeDraft: true, PageSize: 5})
	return dashboardProps{
		User:        user,
		Stats:       s.Stats(),
		RecentPosts: posts,
	}, nil
}

func (p dashboardPage) Page(props dashboardProps) gsx.Node {
	return gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
		_gsxgw := gsx.W(_gsxw)
//line dashboard.gsx:48:2
		_gsxgw.Node(ctx, layout.AdminShell(layout.AdminShellProps{Title: "Dashboard", Current: props.User, Children: gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
			_gsxgw := gsx.W(_gsxw)
//line dashboard.gsx:49:3
			_gsxgw.S("<header")
			_gsxgw.S(" class=\"mb-6 flex items-end justify-between\"")
			_gsxgw.S(">")
//line dashboard.gsx:50:4
			_gsxgw.S("<h1")
			_gsxgw.S(" class=\"text-2xl font-semibold\"")
			_gsxgw.S(">")
			_gsxgw.S("Dashboard")
			_gsxgw.S("</h1>")
//line dashboard.gsx:51:4
			_gsxgw.S("<div")
			_gsxgw.S(" class=\"flex gap-2 text-xs\"")
			_gsxgw.S(">")
//line dashboard.gsx:52:5
			_gsxgw.S("<button")
			_gsxgw.S(" class=\"rounded border px-2 py-1 hover:bg-white\"")
			_gsxv0, _gsxerr := structpages.URLFor(ctx, dashboardPage{})
			if _gsxerr != nil {
				return _gsxerr
			}
			_gsxgw.S(" hx-get=\"")
			_gsxgw.URL(string(_gsxv0))
			_gsxgw.S("\"")
			_gsxv1, _gsxerr := structpages.IDTarget(ctx, StatsGrid)
			if _gsxerr != nil {
				return _gsxerr
			}
			_gsxgw.S(" hx-target=\"")
			_gsxgw.AttrValue(string(_gsxv1))
			_gsxgw.S("\"")
			_gsxgw.S(" hx-swap=\"outerHTML\"")
			_gsxgw.S(">")
			_gsxgw.S("↻ Stats")
			_gsxgw.S("</button>")
//line dashboard.gsx:58:5
			_gsxgw.S("<button")
			_gsxgw.S(" class=\"rounded border px-2 py-1 hover:bg-white\"")
			_gsxv2, _gsxerr := structpages.URLFor(ctx, dashboardPage{})
			if _gsxerr != nil {
				return _gsxerr
			}
			_gsxgw.S(" hx-get=\"")
			_gsxgw.URL(string(_gsxv2))
			_gsxgw.S("\"")
			_gsxv3, _gsxerr := structpages.IDTarget(ctx, RecentPostsCard)
			if _gsxerr != nil {
				return _gsxerr
			}
			_gsxgw.S(" hx-target=\"")
			_gsxgw.AttrValue(string(_gsxv3))
			_gsxgw.S("\"")
			_gsxgw.S(" hx-swap=\"outerHTML\"")
			_gsxgw.S(">")
			_gsxgw.S("↻ Recent posts")
			_gsxgw.S("</button>")
			_gsxgw.S("</div>")
			_gsxgw.S("</header>")
//line dashboard.gsx:66:3
			_gsxgw.S("<section")
			_gsxgw.S(" class=\"space-y-6\"")
			_gsxgw.S(">")
//line dashboard.gsx:67:4
			_gsxgw.Node(ctx, StatsGrid(StatsGridProps{Stats: props.Stats}))
//line dashboard.gsx:68:4
			_gsxgw.Node(ctx, RecentPostsCard(RecentPostsCardProps{Posts: props.RecentPosts}))
//line dashboard.gsx:69:4
			_gsxgw.Node(ctx, components.Card(components.CardProps{Title: "Try it", Children: gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
				_gsxgw := gsx.W(_gsxw)
//line dashboard.gsx:70:5
				_gsxgw.S("<ul")
				_gsxgw.S(" class=\"list-disc space-y-1 pl-5 text-sm text-slate-700\"")
				_gsxgw.S(">")
//line dashboard.gsx:71:6
				_gsxgw.S("<li")
				_gsxgw.S(">")
				_gsxgw.S("Click ↻ Stats — only the StatsGrid widget refreshes (check Network tab).")
				_gsxgw.S("</li>")
//line dashboard.gsx:72:6
				_gsxgw.S("<li")
				_gsxgw.S(">")
				_gsxgw.S("Click ↻ Recent posts — only that card reloads, with its own DB query.")
				_gsxgw.S("</li>")
//line dashboard.gsx:73:6
				_gsxgw.S("<li")
				_gsxgw.S(">")
				_gsxgw.S("Hard refresh — the full document re-renders via Page().")
				_gsxgw.S("</li>")
				_gsxgw.S("</ul>")
				return _gsxgw.Err()
			})}))
			_gsxgw.S("</section>")
			return _gsxgw.Err()
		})}))
		return _gsxgw.Err()
	})
}
