// Code generated by gsx; DO NOT EDIT.

package admin

import (
	"context"
	"io"

	"github.com/gsxhq/gsx"
	"github.com/jackielii/structpages/examples/blog/ui/components"
)

// LoginShell is invoked from login.go (LoginPage.ServeHTTP). gsx requires
// component names to be Capitalized (lowercase = HTML element), so the templ
// `loginShell` becomes `LoginShell`.

type LoginShellProps struct {
	Username string
	ErrMsg   string
}

//line login.gsx:8:1
func LoginShell(_gsxp LoginShellProps) gsx.Node {
	return gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
		username := _gsxp.Username
		errMsg := _gsxp.ErrMsg
		_gsxgw := gsx.W(_gsxw)
		_gsxgw.S("<!DOCTYPE html>")
//line login.gsx:10:2
		_gsxgw.S("<html lang=\"en\">")
//line login.gsx:11:3
		_gsxgw.S("<head>")
//line login.gsx:12:4
		_gsxgw.S("<meta charset=\"utf-8\"/>")
//line login.gsx:13:4
		_gsxgw.S("<title>Sign in — blog admin</title>")
//line login.gsx:14:4
		_gsxgw.S("<script src=\"https://cdn.tailwindcss.com\"></script></head>")
//line login.gsx:16:3
		_gsxgw.S("<body class=\"bg-slate-100 text-slate-900\">")
//line login.gsx:17:4
		_gsxgw.S("<main class=\"mx-auto max-w-sm px-4 py-16\">")
//line login.gsx:18:5
		_gsxgw.Node(ctx, components.Card(components.CardProps{Title: "Sign in", Children: gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
			_gsxgw := gsx.W(_gsxw)
//line login.gsx:19:6
			_gsxgw.S("<form method=\"POST\" class=\"space-y-3\">")
//line login.gsx:20:7
			_gsxgw.Node(ctx, components.Alert(components.AlertProps{Kind: components.AlertError, Msg: errMsg}))
//line login.gsx:24:7
			_gsxgw.S("<label class=\"block text-sm\">")
//line login.gsx:25:8
			_gsxgw.S("<span class=\"mb-1 block font-medium text-slate-700\">Username</span>")
//line login.gsx:28:8
			_gsxgw.S("<input name=\"username\" value=\"")
			_gsxgw.AttrValue(string(username))
			_gsxgw.S("\"")
			_gsxgw.BoolAttr("required", true)
			_gsxgw.BoolAttr("autofocus", true)
			_gsxgw.S(" class=\"w-full rounded border border-slate-300 px-2 py-1.5 text-sm\"/></label>")
//line login.gsx:36:7
			_gsxgw.S("<label class=\"block text-sm\">")
//line login.gsx:37:8
			_gsxgw.S("<span class=\"mb-1 block font-medium text-slate-700\">Password</span>")
//line login.gsx:40:8
			_gsxgw.S("<input type=\"password\" name=\"password\"")
			_gsxgw.BoolAttr("required", true)
			_gsxgw.S(" class=\"w-full rounded border border-slate-300 px-2 py-1.5 text-sm\"/></label>")
//line login.gsx:47:7
			_gsxgw.S("<button type=\"submit\" class=\"inline-flex w-full items-center justify-center rounded bg-slate-900 px-3 py-2 text-sm font-medium text-white hover:bg-slate-700\">Sign in</button>")
//line login.gsx:53:7
			_gsxgw.S("<p class=\"text-xs text-slate-500\">Demo credentials: ")
//line login.gsx:54:26
			_gsxgw.S("<code>admin</code> / ")
//line login.gsx:54:47
			_gsxgw.S("<code>admin</code></p></form>")
			return _gsxgw.Err()
		})}))
		_gsxgw.S("</main></body></html>")
		return _gsxgw.Err()
	})
}
