// Code generated by gsx; DO NOT EDIT.

package admin

import (
	"context"
	"io"

	"github.com/gsxhq/gsx"
	"github.com/jackielii/structpages/examples/blog/ui/components"
)

// LoginShell is invoked from login.go (LoginPage.ServeHTTP). gsx requires
// component names to be Capitalized (lowercase = HTML element), so the templ
// `loginShell` becomes `LoginShell`.

type LoginShellProps struct {
	Username string
	ErrMsg   string
}

func LoginShell(_gsxp LoginShellProps) gsx.Node {
	return gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
		username := _gsxp.Username
		errMsg := _gsxp.ErrMsg
		_gsxgw := gsx.W(_gsxw)
		_gsxgw.S("<!DOCTYPE html>")
//line login.gsx:10:2
		_gsxgw.S("<html")
		_gsxgw.S(" lang=\"en\"")
		_gsxgw.S(">")
//line login.gsx:11:3
		_gsxgw.S("<head")
		_gsxgw.S(">")
//line login.gsx:12:4
		_gsxgw.S("<meta")
		_gsxgw.S(" charset=\"utf-8\"")
		_gsxgw.S("/>")
//line login.gsx:13:4
		_gsxgw.S("<title")
		_gsxgw.S(">")
		_gsxgw.S("Sign in — blog admin")
		_gsxgw.S("</title>")
//line login.gsx:14:4
		_gsxgw.S("<script")
		_gsxgw.S(" src=\"https://cdn.tailwindcss.com\"")
		_gsxgw.S(">")
		_gsxgw.S("</script>")
		_gsxgw.S("</head>")
//line login.gsx:16:3
		_gsxgw.S("<body")
		_gsxgw.S(" class=\"bg-slate-100 text-slate-900\"")
		_gsxgw.S(">")
//line login.gsx:17:4
		_gsxgw.S("<main")
		_gsxgw.S(" class=\"mx-auto max-w-sm px-4 py-16\"")
		_gsxgw.S(">")
//line login.gsx:18:5
		_gsxgw.Node(ctx, components.Card(components.CardProps{Title: "Sign in", Children: gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
			_gsxgw := gsx.W(_gsxw)
//line login.gsx:19:6
			_gsxgw.S("<form")
			_gsxgw.S(" method=\"POST\"")
			_gsxgw.S(" class=\"space-y-3\"")
			_gsxgw.S(">")
//line login.gsx:20:7
			_gsxgw.Node(ctx, components.Alert(components.AlertProps{Kind: components.AlertError, Msg: errMsg}))
//line login.gsx:21:7
			_gsxgw.S("<label")
			_gsxgw.S(" class=\"block text-sm\"")
			_gsxgw.S(">")
//line login.gsx:22:8
			_gsxgw.S("<span")
			_gsxgw.S(" class=\"mb-1 block font-medium text-slate-700\"")
			_gsxgw.S(">")
			_gsxgw.S("Username")
			_gsxgw.S("</span>")
//line login.gsx:23:8
			_gsxgw.S("<input")
			_gsxgw.S(" name=\"username\"")
			_gsxgw.S(" value=\"")
			_gsxgw.AttrValue(string(username))
			_gsxgw.S("\"")
			_gsxgw.BoolAttr("required", true)
			_gsxgw.BoolAttr("autofocus", true)
			_gsxgw.S(" class=\"w-full rounded border border-slate-300 px-2 py-1.5 text-sm\"")
			_gsxgw.S("/>")
			_gsxgw.S("</label>")
//line login.gsx:31:7
			_gsxgw.S("<label")
			_gsxgw.S(" class=\"block text-sm\"")
			_gsxgw.S(">")
//line login.gsx:32:8
			_gsxgw.S("<span")
			_gsxgw.S(" class=\"mb-1 block font-medium text-slate-700\"")
			_gsxgw.S(">")
			_gsxgw.S("Password")
			_gsxgw.S("</span>")
//line login.gsx:33:8
			_gsxgw.S("<input")
			_gsxgw.S(" type=\"password\"")
			_gsxgw.S(" name=\"password\"")
			_gsxgw.BoolAttr("required", true)
			_gsxgw.S(" class=\"w-full rounded border border-slate-300 px-2 py-1.5 text-sm\"")
			_gsxgw.S("/>")
			_gsxgw.S("</label>")
//line login.gsx:40:7
			_gsxgw.S("<button")
			_gsxgw.S(" type=\"submit\"")
			_gsxgw.S(" class=\"inline-flex w-full items-center justify-center rounded bg-slate-900 px-3 py-2 text-sm font-medium text-white hover:bg-slate-700\"")
			_gsxgw.S(">")
			_gsxgw.S("Sign in")
			_gsxgw.S("</button>")
//line login.gsx:46:7
			_gsxgw.S("<p")
			_gsxgw.S(" class=\"text-xs text-slate-500\"")
			_gsxgw.S(">")
			_gsxgw.S("Demo credentials: ")
//line login.gsx:46:59
			_gsxgw.S("<code")
			_gsxgw.S(">")
			_gsxgw.S("admin")
			_gsxgw.S("</code>")
			_gsxgw.S(" / ")
//line login.gsx:46:80
			_gsxgw.S("<code")
			_gsxgw.S(">")
			_gsxgw.S("admin")
			_gsxgw.S("</code>")
			_gsxgw.S("</p>")
			_gsxgw.S("</form>")
			return _gsxgw.Err()
		})}))
		_gsxgw.S("</main>")
		_gsxgw.S("</body>")
		_gsxgw.S("</html>")
		return _gsxgw.Err()
	})
}
