// Code generated by gsx; DO NOT EDIT.

package admin

import (
	"context"
	"fmt"
	"io"
	"net/http"
	"strconv"

	"github.com/gsxhq/gsx"
	_gsxf0 "github.com/jackielii/structpages"
	"github.com/jackielii/structpages/examples/blog/auth"
	"github.com/jackielii/structpages/examples/blog/store"
	"github.com/jackielii/structpages/examples/blog/ui/components"
	"github.com/jackielii/structpages/examples/blog/ui/layout"
)

// AdminShellWith is a tiny gsx wrapper used by handlers that need to render a
// custom body inside AdminShell from Go code. The body is passed as the
// implicit Children prop — from Go: AdminShellWith(AdminShellWithProps{Title: …,
// User: …, Children: body}).

type AdminShellWithProps struct {
	Title    string
	User     store.User
	Children gsx.Node
}

func AdminShellWith(_gsxp AdminShellWithProps) gsx.Node {
	return gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
		title := _gsxp.Title
		user := _gsxp.User
		children := _gsxp.Children
		_gsxgw := gsx.W(_gsxw)
//line posts.gsx:20:2
		_gsxgw.Node(ctx, layout.AdminShell(layout.AdminShellProps{Title: title, Current: user, Children: gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
			_gsxgw := gsx.W(_gsxw)
//line posts.gsx:21:3
			_gsxgw.Node(ctx, children)
			return _gsxgw.Err()
		})}))
		return _gsxgw.Err()
	})
}

// --- List ---

type postListPage struct{}

type postListProps struct {
	User  store.User
	Posts []store.Post
}

func (postListPage) Props(r *http.Request, s *store.Store) (postListProps, error) {
	user, _ := auth.UserFromContext(r.Context())
	posts, _ := s.ListPosts(store.PostFilter{IncludeDraft: true, PageSize: 50})
	return postListProps{User: user, Posts: posts}, nil
}

func (p postListPage) Page(props postListProps) gsx.Node {
	return gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
		_gsxgw := gsx.W(_gsxw)
//line posts.gsx:41:2
		_gsxgw.Node(ctx, layout.AdminShell(layout.AdminShellProps{Title: "Posts", Current: props.User, Children: gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
			_gsxgw := gsx.W(_gsxw)
//line posts.gsx:42:3
			_gsxgw.S("<header class=\"mb-4 flex items-center justify-between\">")
//line posts.gsx:43:4
			_gsxgw.S("<h1 class=\"text-2xl font-semibold\">All posts</h1>")
//line posts.gsx:44:4
			_gsxgw.S("<a class=\"rounded bg-slate-900 px-3 py-1.5 text-sm font-medium text-white hover:bg-slate-700\"")
			_gsxv0, _gsxerr := _gsxf0.URLFor(ctx, (postNewPage{}))
			if _gsxerr != nil {
				return _gsxerr
			}
			_gsxgw.S(" href=\"")
			_gsxgw.URL(string(_gsxv0))
			_gsxgw.S("\">New post</a></header>")
//line posts.gsx:51:3
			_gsxgw.Node(ctx, PostsTable(PostsTableProps{Posts: props.Posts}))
			return _gsxgw.Err()
		})}))
		return _gsxgw.Err()
	})
}

// --- New ---

type postNewPage struct{}

type postFormViewProps struct {
	User       store.User
	Categories []store.Category
	Post       store.Post
}

func (postNewPage) Props(r *http.Request, s *store.Store) (postFormViewProps, error) {
	user, _ := auth.UserFromContext(r.Context())
	return postFormViewProps{User: user, Categories: s.ListCategories()}, nil
}

func (p postNewPage) Page(props postFormViewProps) gsx.Node {
	return gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
		_gsxgw := gsx.W(_gsxw)
//line posts.gsx:71:2
		_gsxgw.Node(ctx, layout.AdminShell(layout.AdminShellProps{Title: "New post", Current: props.User, Children: gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
			_gsxgw := gsx.W(_gsxw)
//line posts.gsx:72:3
			_gsxgw.S("<h1 class=\"mb-4 text-2xl font-semibold\">New post</h1>")
//line posts.gsx:73:3
			_gsxgw.Node(ctx, PostForm(PostFormProps{P: props.Post, Cats: props.Categories, ErrMsg: ""}))
			return _gsxgw.Err()
		})}))
		return _gsxgw.Err()
	})
}

// --- Edit ---

type postEditPage struct{}

func (postEditPage) Props(r *http.Request, s *store.Store) (postFormViewProps, error) {
	user, _ := auth.UserFromContext(r.Context())
	id, err := strconv.Atoi(r.PathValue("id"))
	if err != nil {
		return postFormViewProps{}, fmt.Errorf("invalid post id: %w", err)
	}
	p, err := s.GetPost(id)
	if err != nil {
		return postFormViewProps{}, err
	}
	return postFormViewProps{User: user, Categories: s.ListCategories(), Post: p}, nil
}

func (p postEditPage) Page(props postFormViewProps) gsx.Node {
	return gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
		_gsxgw := gsx.W(_gsxw)
//line posts.gsx:95:2
		_gsxgw.Node(ctx, layout.AdminShell(layout.AdminShellProps{Title: "Edit post", Current: props.User, Children: gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
			_gsxgw := gsx.W(_gsxw)
//line posts.gsx:96:3
			_gsxgw.S("<h1 class=\"mb-4 text-2xl font-semibold\">Edit post</h1>")
//line posts.gsx:97:3
			_gsxgw.Node(ctx, PostForm(PostFormProps{P: props.Post, Cats: props.Categories, ErrMsg: ""}))
			return _gsxgw.Err()
		})}))
		return _gsxgw.Err()
	})
}

// --- Shared form ---

type PostFormProps struct {
	P      store.Post
	Cats   []store.Category
	ErrMsg string
	Attrs  gsx.Attrs
}

func PostForm(_gsxp PostFormProps) gsx.Node {
	return gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
		p := _gsxp.P
		cats := _gsxp.Cats
		errMsg := _gsxp.ErrMsg
		_gsxgw := gsx.W(_gsxw)
//line posts.gsx:104:2
		_gsxgw.S("<form")
		if !_gsxp.Attrs.Has("method") {
			_gsxgw.S(" method=\"POST\"")
		}
		if !_gsxp.Attrs.Has("action") {
			_gsxgw.S(" action=\"")
			_gsxgw.URL(string(postFormAction(ctx, p)))
			_gsxgw.S("\"")
		}
		_gsxgw.S(" class=\"")
		_gsxgw.Class(gsx.Class("space-y-3"), gsx.Class(_gsxp.Attrs.Class()))
		_gsxgw.S("\"")
		_gsxgw.StyleMerged("", _gsxp.Attrs.Style())
		_gsxgw.Spread(ctx, _gsxp.Attrs.Without("class", "style"))
		_gsxgw.S(">")
//line posts.gsx:105:3
		_gsxgw.Node(ctx, components.Alert(components.AlertProps{Kind: components.AlertError, Msg: errMsg}))
//line posts.gsx:106:3
		_gsxgw.Node(ctx, components.Input(components.InputProps{Name: "title", Label: "Title", Value: p.Title, ErrMsg: ""}))
//line posts.gsx:107:3
		_gsxgw.Node(ctx, components.Input(components.InputProps{Name: "slug", Label: "Slug (auto if blank)", Value: p.Slug, ErrMsg: ""}))
//line posts.gsx:113:3
		_gsxgw.S("<label class=\"block text-sm\">")
//line posts.gsx:114:4
		_gsxgw.S("<span class=\"mb-1 block font-medium text-slate-700\">Category</span>")
//line posts.gsx:115:4
		_gsxgw.S("<select name=\"category_id\" class=\"w-full rounded border border-slate-300 px-2 py-1.5 text-sm\">")
//line posts.gsx:119:5
		_gsxgw.S("<option value=\"0\">— pick one —</option>")
//line posts.gsx:120:5
		for _, c := range cats {
//line posts.gsx:121:6
			_gsxgw.S("<option value=\"")
			_gsxgw.AttrValue(strconv.FormatInt(int64(c.ID), 10))
			_gsxgw.S("\"")
			_gsxgw.BoolAttr("selected", bool(c.ID == p.CategoryID))
			_gsxgw.S(">")
//line posts.gsx:122:7
			_gsxgw.Text(string(c.Name))
			_gsxgw.S("</option>")
		}
		_gsxgw.S("</select></label>")
//line posts.gsx:127:3
		_gsxgw.Node(ctx, components.Textarea(components.TextareaProps{Name: "body", Label: "Body", Value: p.Body, ErrMsg: ""}))
//line posts.gsx:128:3
		_gsxgw.S("<label class=\"flex items-center gap-2 text-sm\">")
//line posts.gsx:129:4
		_gsxgw.S("<input type=\"checkbox\" name=\"published\"")
		_gsxgw.BoolAttr("checked", bool(p.Published))
		_gsxgw.S("/>Publish immediately</label>")
//line posts.gsx:132:3
		_gsxgw.S("<div class=\"flex items-center gap-2\">")
//line posts.gsx:133:4
		_gsxgw.Node(ctx, components.Button(components.ButtonProps{Label: "Save", Attrs: gsx.Attrs{}.Merge(gsx.Attrs{"type": "submit"})}))
//line posts.gsx:134:4
		_gsxgw.S("<a class=\"text-sm text-slate-500 hover:underline\"")
		_gsxv1, _gsxerr := _gsxf0.URLFor(ctx, (postListPage{}))
		if _gsxerr != nil {
			return _gsxerr
		}
		_gsxgw.S(" href=\"")
		_gsxgw.URL(string(_gsxv1))
		_gsxgw.S("\">Cancel</a></div></form>")
		return _gsxgw.Err()
	})
}
