version: "2"
run:
  tests: true
linters:
  enable:
    - dupl
    - gocognit
    - gocritic
    - gocyclo
    - gosec
    - lll
    - misspell
    - prealloc
    - unconvert
  settings:
    dupl:
      threshold: 100
    gocognit:
      min-complexity: 45
    gocritic:
      disabled-checks:
        - dupImport
        - ifElseChain
        - octalLiteral
        - whyNoLint
        - wrapperFunc
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 20
    govet:
      enable:
        - shadow
    lll:
      line-length: 120
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - gocognit
          - gocritic
          - gosec
          - staticcheck
          - unused
        path: _test\.go
      - linters:
          - gocognit
          - staticcheck
          - unused
        path: examples
    paths:
      - vendor
      - examples
      - third_party$
      - builtin$
      - examples$
formatters:
  settings:
    goimports:
      local-prefixes:
        - github.com/jackielii/structpages
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
