version: 2

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused
    - misspell
    - gosec
    - prealloc
    - unconvert
    - gocritic
    - gocyclo
    - gocognit
    - dupl
    - lll

formatters:
  enable:
    - gofmt
    - goimports

linters-settings:
  goimports:
    local-prefixes: github.com/jackielii/structpages

  govet:
    enable:
      - shadow

  gocyclo:
    min-complexity: 15

  gocognit:
    min-complexity: 20

  dupl:
    threshold: 100

  lll:
    line-length: 120

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - gocognit
    - path: _test\.go
      linters:
        - unused
      text: "field .* is unused"

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - examples

