// Code generated by gsx; DO NOT EDIT.

package main

import (
	"context"
	"fmt"
	"io"
	"strconv"

	"github.com/gsxhq/gsx"
)

// BadLinks mirrors the templ original — it deliberately uses hard-coded
// internal URLs so the structpages-lint [url-attr] rule has targets to flag.
// In gsx the component uses inline params just like the templ version.
//
// NOTE ON gsx AUTO-ESCAPING: gsx escapes URL-context attributes
// (href, hx-get, action, …) by context. That means a dynamically-
// constructed javascript: or data: URL would be neutralised, preventing
// XSS via URL sinks. However, the [url-attr] lint rule catches a
// different problem — routing-correctness: hard-coded path strings that
// bypass structpages.URLFor break when routes are renamed. That class of
// bug is orthogonal to XSS escaping, so gsx's auto-escaping does NOT
// make these findings go away. The lint still has value in gsx projects.

type BadLinksProps struct {
	Id   int
	Name string
}

func BadLinks(_gsxp BadLinksProps) gsx.Node {
	return gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
		id := _gsxp.Id
		name := _gsxp.Name
		_gsxgw := gsx.W(_gsxw)
//line pages.gsx:21:2
		_gsxgw.S("<a href=\"/login\">Hard-coded internal</a>")
//line pages.gsx:22:2
		_gsxgw.S("<a href=\"")
		_gsxgw.URL(string("/" + "admin"))
		_gsxgw.S("\">Expression literal</a>")
//line pages.gsx:23:2
		_gsxgw.S("<a href=\"")
		_gsxgw.URL(string("/items/" + strconv.Itoa(id)))
		_gsxgw.S("\">Concat</a>")
//line pages.gsx:24:2
		_gsxgw.S("<a href=\"")
		_gsxgw.URL(string(fmt.Sprintf("/users/%s", name)))
		_gsxgw.S("\">Sprintf</a>")
//line pages.gsx:25:2
		_gsxgw.S("<a hx-get=\"")
		_gsxgw.URL(string("/api/items"))
		_gsxgw.S("\">Bad hx-get</a>")
//line pages.gsx:26:2
		_gsxgw.S("<form action=\"")
		_gsxgw.URL(string("/submit"))
		_gsxgw.S("\">Bad action</form>")
//line pages.gsx:27:2
		_gsxgw.S("<a href=\"https://example.com/external\">External (allowed)</a>")
		return _gsxgw.Err()
	})
}
