// Code generated by gsx; DO NOT EDIT.

package blog

import (
	"context"
	"io"
	"net/http"
	"strconv"

	"github.com/gsxhq/gsx"
	"github.com/jackielii/structpages/examples/blog/store"
	"github.com/jackielii/structpages/examples/blog/ui/components"
	"github.com/jackielii/structpages/examples/blog/ui/layout"
)

type categoryPage struct{}

type categoryProps struct {
	Category   store.Category
	Posts      []store.Post
	Pagination components.PageNav
}

func (categoryPage) Props(r *http.Request, s *store.Store) (categoryProps, error) {
	slug := r.PathValue("slug")
	cat, err := s.GetCategoryBySlug(slug)
	if err != nil {
		return categoryProps{}, err
	}
	page, _ := strconv.Atoi(r.URL.Query().Get("page"))
	if page < 1 {
		page = 1
	}
	posts, total := s.ListPosts(store.PostFilter{
		CategoryID: cat.ID,
		Page:       page,
		PageSize:   store.DefaultPageSize,
	})

	ctx := r.Context()
	return categoryProps{
		Category: cat,
		Posts:    posts,
		Pagination: components.PageNav{
			Page:     page,
			PageSize: store.DefaultPageSize,
			Total:    total,
			URL: func(target int) (string, error) {
				return components.URL(ctx,
					[]any{categoryPage{}, "?page={page}"},
					"page", target,
				)
			},
		},
	}, nil
}

//line category.gsx:54:1
func (p categoryPage) Page(props categoryProps) gsx.Node {
	return gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
		_gsxgw := gsx.W(_gsxw)
//line category.gsx:55:2
		_gsxgw.Node(ctx, layout.PublicShell(layout.PublicShellProps{Title: props.Category.Name, Children: gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
			_gsxgw := gsx.W(_gsxw)
//line category.gsx:56:3
			_gsxgw.S("<h1 class=\"mb-1 text-2xl font-semibold\">")
//line category.gsx:56:43
			_gsxgw.Text(string(props.Category.Name))
			_gsxgw.S("</h1>")
//line category.gsx:57:3
			_gsxgw.S("<p class=\"mb-6 text-sm text-slate-500\">Posts filed under this category.</p>")
//line category.gsx:60:3
			_gsxgw.S("<div class=\"space-y-4\">")
//line category.gsx:61:4
			if len(props.Posts) == 0 {
//line category.gsx:62:5
				_gsxgw.S("<p class=\"text-sm text-slate-500\">Nothing here yet.</p>")
			}
//line category.gsx:64:4
			for _, post := range props.Posts {
//line category.gsx:65:5
				_gsxgw.Node(ctx, PostCard(PostCardProps{P: post}))
			}
			_gsxgw.S("</div>")
//line category.gsx:68:3
			_gsxgw.S("<div class=\"mt-6\">")
//line category.gsx:68:21
			_gsxgw.Node(ctx, components.Pagination(props.Pagination))
			_gsxgw.S("</div>")
			return _gsxgw.Err()
		})}))
		return _gsxgw.Err()
	})
}
