// Code generated by gsx; DO NOT EDIT.

package blog

import (
	"net/http"
	"strconv"

	_gsxctx "context"
	_gsxrt "github.com/gsxhq/gsx"
	"github.com/jackielii/structpages"
	"github.com/jackielii/structpages/examples/blog/store"
	"github.com/jackielii/structpages/examples/blog/ui/components"
	"github.com/jackielii/structpages/examples/blog/ui/layout"
	_gsxio "io"
)

//line category.gsx:13:1
type categoryPage struct{}

type categoryProps struct {
	Category   store.Category
	Posts      []store.Post
	Pagination components.PageNav
}

func (categoryPage) Props(r *http.Request, s *store.Store) (categoryProps, error) {
	slug := r.PathValue("slug")
	cat, err := s.GetCategoryBySlug(slug)
	if err != nil {
		return categoryProps{}, err
	}
	page, _ := strconv.Atoi(r.URL.Query().Get("page"))
	if page < 1 {
		page = 1
	}
	posts, total := s.ListPosts(store.PostFilter{
		CategoryID: cat.ID,
		Page:       page,
		PageSize:   store.DefaultPageSize,
	})

	ctx := r.Context()
	return categoryProps{
		Category: cat,
		Posts:    posts,
		Pagination: components.PageNav{
			Page:     page,
			PageSize: store.DefaultPageSize,
			Total:    total,
			URL: func(target int) (string, error) {
				return structpages.URLFor(ctx,
					[]any{categoryPage{}, "?page={page}"},
					"slug", cat.Slug,
					"page", target,
				)
			},
		},
	}, nil
}

//line category.gsx:56:1
func (p categoryPage) Page(props categoryProps) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line category.gsx:57:2
		_gsxgw.Node(ctx, layout.PublicShell(props.Category.Name, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
			_gsxgw := _gsxrt.W(_gsxw)
//line category.gsx:58:3
			_gsxgw.S("<h1 class=\"mb-1 text-2xl font-semibold\">")
//line category.gsx:58:43
			_gsxgw.Text(string(props.Category.Name))
			_gsxgw.S("</h1>")
//line category.gsx:59:3
			_gsxgw.S("<p class=\"mb-6 text-sm text-slate-500\">Posts filed under this category.</p>")
//line category.gsx:62:3
			_gsxgw.S("<div class=\"space-y-4\">")
//line category.gsx:63:4
			if len(props.Posts) == 0 {
//line category.gsx:64:5
				_gsxgw.S("<p class=\"text-sm text-slate-500\">Nothing here yet.</p>")
			}
//line category.gsx:66:4
			for _, post := range props.Posts {
//line category.gsx:67:5
				_gsxgw.NodeResult(_gsxrenderPostCard(ctx, _gsxgw, post))
			}
			_gsxgw.S("</div>")
//line category.gsx:70:3
			_gsxgw.S("<div class=\"mt-6\">")
//line category.gsx:71:4
			_gsxgw.Node(ctx, components.Pagination(props.Pagination))
			_gsxgw.S("</div>")
			return _gsxgw.Err()
		})))
		return _gsxgw.Err()
	})
}
