// Code generated by gsx; DO NOT EDIT.

package blog

import (
	"context"
	"io"
	"strconv"

	"github.com/gsxhq/gsx"
	_gsxf0 "github.com/jackielii/structpages"
	"github.com/jackielii/structpages/examples/blog/store"
)

type PostMetaProps struct {
	P     store.Post
	Attrs gsx.Attrs
}

//line components.gsx:11:1
func PostMeta(_gsxp PostMetaProps) gsx.Node {
	return gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
		p := _gsxp.P
		_gsxgw := gsx.W(_gsxw)
//line components.gsx:12:2
		_gsxgw.S("<p class=\"")
		_gsxgw.Class(gsx.Class("text-xs text-slate-500"), gsx.Class(_gsxp.Attrs.Class()))
		_gsxgw.S("\"")
		_gsxgw.StyleMerged("", _gsxp.Attrs.Style())
		_gsxgw.Spread(ctx, _gsxp.Attrs.Without("class", "style"))
		_gsxgw.S(">Posted ")
//line components.gsx:13:10
		_gsxgw.Text(string(p.CreatedAt.Format("Jan 2, 2006")))
		_gsxgw.S("</p>")
		return _gsxgw.Err()
	})
}

type PostCardProps struct {
	P     store.Post
	Attrs gsx.Attrs
}

//line components.gsx:17:1
func PostCard(_gsxp PostCardProps) gsx.Node {
	return gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
		p := _gsxp.P
		_gsxgw := gsx.W(_gsxw)
//line components.gsx:18:2
		_gsxgw.S("<article class=\"")
		_gsxgw.Class(gsx.Class("rounded-lg border bg-white p-5 shadow-sm"), gsx.Class(_gsxp.Attrs.Class()))
		_gsxgw.S("\"")
		_gsxgw.StyleMerged("", _gsxp.Attrs.Style())
		_gsxgw.Spread(ctx, _gsxp.Attrs.Without("class", "style"))
		_gsxgw.S(">")
//line components.gsx:19:3
		_gsxgw.S("<a class=\"text-lg font-semibold text-slate-900 hover:underline\"")
		_gsxv0, _gsxerr := _gsxf0.URLFor(ctx, (postPage{}), "slug", p.Slug)
		if _gsxerr != nil {
			return _gsxerr
		}
		_gsxgw.S(" href=\"")
		_gsxgw.URL(string(_gsxv0))
		_gsxgw.S("\">")
//line components.gsx:23:4
		_gsxgw.Text(string(p.Title))
		_gsxgw.S("</a>")
//line components.gsx:25:3
		_gsxgw.Node(ctx, PostMeta(PostMetaProps{P: p}))
//line components.gsx:26:3
		_gsxgw.S("<p class=\"mt-2 line-clamp-2 text-sm text-slate-700\">")
//line components.gsx:26:55
		_gsxgw.Text(string(p.Body))
		_gsxgw.S("</p></article>")
		return _gsxgw.Err()
	})
}

// CommentsList is a standalone function component so the commentHandler
// can re-render it from ServeHTTP via RenderComponent(CommentsList(...)).
// It owns its own wrapper id, which doubles as the HTMX hx-target.

type CommentsListProps struct {
	Comments []store.Comment
	Attrs    gsx.Attrs
}

//line components.gsx:33:1
func CommentsList(_gsxp CommentsListProps) gsx.Node {
	return gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
		comments := _gsxp.Comments
		_gsxgw := gsx.W(_gsxw)
//line components.gsx:34:2
		_gsxgw.S("<div")
		if !_gsxp.Attrs.Has("id") {
			_gsxv1, _gsxerr := _gsxf0.ID(ctx, (CommentsList))
			if _gsxerr != nil {
				return _gsxerr
			}
			_gsxgw.S(" id=\"")
			_gsxgw.AttrValue(string(_gsxv1))
			_gsxgw.S("\"")
		}
		_gsxgw.S(" class=\"")
		_gsxgw.Class(gsx.Class("space-y-3"), gsx.Class(_gsxp.Attrs.Class()))
		_gsxgw.S("\"")
		_gsxgw.StyleMerged("", _gsxp.Attrs.Style())
		_gsxgw.Spread(ctx, _gsxp.Attrs.Without("class", "style"))
		_gsxgw.S(">")
//line components.gsx:35:3
		if len(comments) == 0 {
//line components.gsx:36:4
			_gsxgw.S("<p class=\"text-sm text-slate-500\">No comments yet — be the first.</p>")
		}
//line components.gsx:40:3
		for _, c := range comments {
//line components.gsx:41:4
			_gsxgw.S("<article class=\"rounded border bg-slate-50 p-3\">")
//line components.gsx:42:5
			_gsxgw.S("<header class=\"text-xs font-medium text-slate-700\">")
//line components.gsx:43:6
			_gsxgw.Text(string(c.Author))
			_gsxgw.S(" · ")
//line components.gsx:43:22
			_gsxgw.Text(string(c.CreatedAt.Format("15:04 Jan 2")))
			_gsxgw.S("</header>")
//line components.gsx:45:5
			_gsxgw.S("<p class=\"mt-1 text-sm text-slate-800\">")
//line components.gsx:45:44
			_gsxgw.Text(string(c.Body))
			_gsxgw.S("</p></article>")
		}
//line components.gsx:48:3
		_gsxgw.S("<p class=\"text-xs text-slate-400\">Total: ")
//line components.gsx:48:44
		_gsxgw.Text(strconv.FormatInt(int64(len(comments)), 10))
		_gsxgw.S("</p></div>")
		return _gsxgw.Err()
	})
}
