// Code generated by gsx; DO NOT EDIT.

package blog

import (
	"context"
	"io"
	"net/http"

	"github.com/gsxhq/gsx"
	"github.com/jackielii/structpages/examples/blog/store"
	"github.com/jackielii/structpages/examples/blog/ui/components"
	"github.com/jackielii/structpages/examples/blog/ui/layout"
)

type homePage struct{}

type homeProps struct {
	Posts      []store.Post
	Categories []store.Category
}

// Props loads page data. Returns homeProps directly — gsx now emits method
// components as func (p homePage) Page(props homeProps) gsx.Node without a wrapper struct.
func (homePage) Props(_ *http.Request, s *store.Store) (homeProps, error) {
	posts, _ := s.ListPosts(store.PostFilter{PageSize: 5})
	return homeProps{Posts: posts, Categories: s.ListCategories()}, nil
}

// Page renders the full document. The former Content() method is inlined here:
// gsx's generated-props wrapping makes a separate Content(props) method
// undispatchable by structpages alongside Page(props) (both would need the same
// single Props-return type). See GAP notes.

func (p homePage) Page(props homeProps) gsx.Node {
	return gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
		_gsxgw := gsx.W(_gsxw)
//line home.gsx:30:2
		_gsxgw.Node(ctx, layout.PublicShell(layout.PublicShellProps{Title: "Home", Children: gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
			_gsxgw := gsx.W(_gsxw)
//line home.gsx:31:3
			_gsxgw.S("<h1")
			_gsxgw.S(" class=\"mb-4 text-2xl font-semibold\"")
			_gsxgw.S(">")
			_gsxgw.S("Recent Posts")
			_gsxgw.S("</h1>")
//line home.gsx:32:3
			_gsxgw.S("<div")
			_gsxgw.S(" class=\"space-y-4\"")
			_gsxgw.S(">")
//line home.gsx:33:4
			for _, post := range props.Posts {
//line home.gsx:34:5
				_gsxgw.Node(ctx, PostCard(PostCardProps{P: post}))
			}
			_gsxgw.S("</div>")
//line home.gsx:37:3
			_gsxgw.Node(ctx, components.Card(components.CardProps{Title: "Browse by category", Children: gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
				_gsxgw := gsx.W(_gsxw)
//line home.gsx:38:4
				_gsxgw.S("<ul")
				_gsxgw.S(" class=\"flex flex-wrap gap-2\"")
				_gsxgw.S(">")
//line home.gsx:39:5
				for _, c := range props.Categories {
//line home.gsx:40:6
					_gsxgw.S("<li")
					_gsxgw.S(">")
//line home.gsx:41:7
					_gsxgw.S("<a")
					_gsxgw.S(" class=\"rounded-full border px-3 py-1 text-sm hover:bg-slate-50\"")
					_gsxv0, _gsxerr := components.URL(ctx, categoryPage{}, "slug", c.Slug)
					if _gsxerr != nil {
						return _gsxerr
					}
					_gsxgw.S(" href=\"")
					_gsxgw.URL(string(_gsxv0))
					_gsxgw.S("\"")
					_gsxgw.S(">")
//line home.gsx:42:8
					_gsxgw.Text(string(c.Name))
					_gsxgw.S("</a>")
					_gsxgw.S("</li>")
				}
				_gsxgw.S("</ul>")
				return _gsxgw.Err()
			})}))
			return _gsxgw.Err()
		})}))
		return _gsxgw.Err()
	})
}
