// Code generated by gsx; DO NOT EDIT.

package blog

import (
	"context"
	"io"
	"net/http"

	"github.com/gsxhq/gsx"
	"github.com/jackielii/structpages"
	"github.com/jackielii/structpages/examples/blog/store"
	"github.com/jackielii/structpages/examples/blog/ui/components"
	"github.com/jackielii/structpages/examples/blog/ui/layout"
)

type postPage struct{}

type postProps struct {
	Post     store.Post
	Author   store.User
	Category store.Category
	Comments []store.Comment
}

func (postPage) Props(r *http.Request, s *store.Store) (postProps, error) {
	slug := r.PathValue("slug")
	p, err := s.GetPostBySlug(slug)
	if err != nil {
		return postProps{}, err
	}
	author, _ := s.GetUser(p.AuthorID)
	category, _ := s.GetCategory(p.CategoryID)
	return postProps{
		Post:     p,
		Author:   author,
		Category: category,
		Comments: s.ListComments(p.ID),
	}, nil
}

func (p postPage) Page(props postProps) gsx.Node {
	return gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
		_gsxgw := gsx.W(_gsxw)
//line post.gsx:39:2
		_gsxgw.Node(ctx, layout.PublicShell(layout.PublicShellProps{Title: props.Post.Title, Children: gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
			_gsxgw := gsx.W(_gsxw)
//line post.gsx:40:3
			_gsxgw.S("<article")
			_gsxgw.S(" class=\"space-y-3\"")
			_gsxgw.S(">")
//line post.gsx:41:4
			_gsxgw.S("<h1")
			_gsxgw.S(" class=\"text-2xl font-semibold\"")
			_gsxgw.S(">")
//line post.gsx:41:39
			_gsxgw.Text(string(props.Post.Title))
			_gsxgw.S("</h1>")
//line post.gsx:42:4
			_gsxgw.S("<p")
			_gsxgw.S(" class=\"text-sm text-slate-500\"")
			_gsxgw.S(">")
			_gsxgw.S("by ")
//line post.gsx:43:8
			_gsxgw.Text(string(props.Author.Username))
//line post.gsx:44:5
			if props.Category.Slug != "" {
				_gsxgw.S("· ")
//line post.gsx:45:9
				_gsxgw.S("<a")
				_gsxgw.S(" class=\"hover:underline\"")
				_gsxv0, _gsxerr := components.URL(ctx, categoryPage{}, "slug", props.Category.Slug)
				if _gsxerr != nil {
					return _gsxerr
				}
				_gsxgw.S(" href=\"")
				_gsxgw.URL(string(_gsxv0))
				_gsxgw.S("\"")
				_gsxgw.S(">")
//line post.gsx:45:110
				_gsxgw.Text(string(props.Category.Name))
				_gsxgw.S("</a>")
			}
			_gsxgw.S("</p>")
//line post.gsx:48:4
			_gsxgw.S("<div")
			_gsxgw.S(" class=\"prose max-w-none text-slate-800\"")
			_gsxgw.S(">")
//line post.gsx:49:5
			_gsxgw.S("<p")
			_gsxgw.S(">")
//line post.gsx:49:8
			_gsxgw.Text(string(props.Post.Body))
			_gsxgw.S("</p>")
			_gsxgw.S("</div>")
			_gsxgw.S("</article>")
//line post.gsx:52:3
			_gsxgw.S("<section")
			_gsxgw.S(" class=\"mt-10 space-y-4\"")
			_gsxgw.S(">")
//line post.gsx:53:4
			_gsxgw.S("<h2")
			_gsxgw.S(" class=\"text-lg font-semibold\"")
			_gsxgw.S(">")
			_gsxgw.S("Comments")
			_gsxgw.S("</h2>")
//line post.gsx:54:4
			_gsxgw.Node(ctx, CommentsList(CommentsListProps{Comments: props.Comments}))
//line post.gsx:55:4
			_gsxgw.S("<form")
			_gsxgw.S(" class=\"space-y-2 rounded border bg-white p-4\"")
			_gsxv1, _gsxerr := structpages.URLFor(ctx, commentHandler{}, "slug", props.Post.Slug)
			if _gsxerr != nil {
				return _gsxerr
			}
			_gsxgw.S(" hx-post=\"")
			_gsxgw.URL(string(_gsxv1))
			_gsxgw.S("\"")
			_gsxv2, _gsxerr := structpages.IDTarget(ctx, CommentsList)
			if _gsxerr != nil {
				return _gsxerr
			}
			_gsxgw.S(" hx-target=\"")
			_gsxgw.AttrValue(string(_gsxv2))
			_gsxgw.S("\"")
			_gsxgw.S(" hx-swap=\"outerHTML\"")
			_gsxgw.S(" hx-on:htmx:after-request=\"this.reset()\"")
			_gsxgw.S(">")
//line post.gsx:62:5
			_gsxgw.S("<h3")
			_gsxgw.S(" class=\"text-sm font-semibold\"")
			_gsxgw.S(">")
			_gsxgw.S("Add a comment")
			_gsxgw.S("</h3>")
//line post.gsx:63:5
			_gsxgw.Node(ctx, components.Input(components.InputProps{Name: "author", Label: "Name", Value: "", ErrMsg: ""}))
//line post.gsx:64:5
			_gsxgw.Node(ctx, components.Textarea(components.TextareaProps{Name: "body", Label: "Comment", Value: "", ErrMsg: ""}))
//line post.gsx:65:5
			_gsxgw.Node(ctx, components.Button(components.ButtonProps{Label: "Post comment", Attrs: gsx.Attrs{}.Merge(gsx.Attrs{"type": "submit"})}))
			_gsxgw.S("</form>")
			_gsxgw.S("</section>")
			return _gsxgw.Err()
		})}))
		return _gsxgw.Err()
	})
}
