// Code generated by gsx; DO NOT EDIT.

package blog

import (
	"context"
	"io"
	"net/http"

	"github.com/gsxhq/gsx"
	"github.com/jackielii/structpages"
	_gsxf0 "github.com/jackielii/structpages"
	"github.com/jackielii/structpages/examples/blog/store"
	"github.com/jackielii/structpages/examples/blog/ui/layout"
)

type searchPage struct{}

type searchProps struct {
	Query string
	Posts []store.Post
}

// Props uses RenderTarget to load less when HTMX only wants the results
// fragment. On the initial page load it returns the full searchProps; when the
// Results fragment is targeted it renders just that component via RenderComponent.
func (p searchPage) Props(r *http.Request, s *store.Store, target structpages.RenderTarget) (searchProps, error) {
	q := r.URL.Query().Get("q")
	sp := searchProps{Query: q}
	if q != "" {
		sp.Posts, _ = s.ListPosts(store.PostFilter{Search: q})
	}
	if target.Is(p.Results) {
		return searchProps{}, structpages.RenderComponent(p.Results(sp))
	}
	return sp, nil
}

//line search.gsx:33:1
func (p searchPage) Page(props searchProps) gsx.Node {
	return gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
		_gsxgw := gsx.W(_gsxw)
//line search.gsx:34:2
		_gsxgw.Node(ctx, layout.PublicShell(layout.PublicShellProps{Title: "Search", Children: gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
			_gsxgw := gsx.W(_gsxw)
//line search.gsx:35:3
			_gsxgw.S("<h1 class=\"mb-4 text-2xl font-semibold\">Search</h1>")
//line search.gsx:36:3
			_gsxgw.S("<form class=\"mb-6\"")
			_gsxv0, _gsxerr := _gsxf0.URLFor(ctx, (searchPage{}))
			if _gsxerr != nil {
				return _gsxerr
			}
			_gsxgw.S(" hx-get=\"")
			_gsxgw.URL(string(_gsxv0))
			_gsxgw.S("\"")
			_gsxv1, _gsxerr := _gsxf0.IDTarget(ctx, (p.Results))
			if _gsxerr != nil {
				return _gsxerr
			}
			_gsxgw.S(" hx-target=\"")
			_gsxgw.AttrValue(string(_gsxv1))
			_gsxgw.S("\" hx-swap=\"outerHTML\" hx-trigger=\"input changed delay:250ms from:input, submit\" hx-push-url=\"true\">")
//line search.gsx:44:4
			_gsxgw.S("<input name=\"q\" value=\"")
			_gsxgw.AttrValue(string(props.Query))
			_gsxgw.S("\" placeholder=\"Search posts...\" class=\"w-full rounded border border-slate-300 px-3 py-2 text-sm\"")
			_gsxgw.BoolAttr("autofocus", true)
			_gsxgw.S("/></form>")
//line search.gsx:52:3
			_gsxgw.Node(ctx, p.Results(props))
			return _gsxgw.Err()
		})}))
		return _gsxgw.Err()
	})
}

//line search.gsx:56:1
func (p searchPage) Results(props searchProps) gsx.Node {
	return gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
		_gsxgw := gsx.W(_gsxw)
//line search.gsx:57:2
		_gsxgw.S("<div")
		_gsxv2, _gsxerr := _gsxf0.ID(ctx, (searchPage.Results))
		if _gsxerr != nil {
			return _gsxerr
		}
		_gsxgw.S(" id=\"")
		_gsxgw.AttrValue(string(_gsxv2))
		_gsxgw.S("\" class=\"space-y-4\">")
//line search.gsx:58:3
		if props.Query == "" {
//line search.gsx:59:4
			_gsxgw.S("<p class=\"text-sm text-slate-500\">Type a query to search.</p>")
		} else {
//line search.gsx:60:10
			if len(props.Posts) == 0 {
//line search.gsx:61:4
				_gsxgw.S("<p class=\"text-sm text-slate-500\">No results for \"")
//line search.gsx:63:5
				_gsxgw.Text(string(props.Query))
				_gsxgw.S("\".</p>")
			} else {
//line search.gsx:67:4
				_gsxgw.S("<p class=\"text-xs text-slate-500\">")
//line search.gsx:68:5
				_gsxgw.Text(string(resultsCount(len(props.Posts))))
				_gsxgw.S("</p>")
//line search.gsx:70:4
				for _, post := range props.Posts {
//line search.gsx:71:5
					_gsxgw.Node(ctx, PostCard(PostCardProps{P: post}))
				}
			}
		}
		_gsxgw.S("</div>")
		return _gsxgw.Err()
	})
}
