// Code generated by gsx; DO NOT EDIT.

package blog

import (
	"context"
	"io"
	"net/http"

	"github.com/gsxhq/gsx"
	"github.com/jackielii/structpages"
	_gsxf0 "github.com/jackielii/structpages"
	"github.com/jackielii/structpages/examples/blog/store"
	"github.com/jackielii/structpages/examples/blog/ui/layout"
)

type searchPage struct{}

type searchProps struct {
	Query string
	Posts []store.Post
}

// Props uses RenderTarget to load less when HTMX only wants the results
// fragment. On the initial page load it returns the full searchProps; when the
// Results fragment is targeted it renders just that component via RenderComponent.
func (p searchPage) Props(r *http.Request, s *store.Store, target structpages.RenderTarget) (searchProps, error) {
	q := r.URL.Query().Get("q")
	sp := searchProps{Query: q}
	if q != "" {
		sp.Posts, _ = s.ListPosts(store.PostFilter{Search: q})
	}
	if target.Is(p.Results) {
		return searchProps{}, structpages.RenderComponent(p.Results(sp))
	}
	return sp, nil
}

func (p searchPage) Page(props searchProps) gsx.Node {
	return gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
		_gsxgw := gsx.W(_gsxw)
//line search.gsx:34:2
		_gsxgw.Node(ctx, layout.PublicShell(layout.PublicShellProps{Title: "Search", Children: gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
			_gsxgw := gsx.W(_gsxw)
//line search.gsx:35:3
			_gsxgw.S("<h1")
			_gsxgw.S(" class=\"mb-4 text-2xl font-semibold\"")
			_gsxgw.S(">")
			_gsxgw.S("Search")
			_gsxgw.S("</h1>")
//line search.gsx:36:3
			_gsxgw.S("<form")
			_gsxgw.S(" class=\"mb-6\"")
			_gsxv0, _gsxerr := _gsxf0.URLFor(ctx, (searchPage{}))
			if _gsxerr != nil {
				return _gsxerr
			}
			_gsxgw.S(" hx-get=\"")
			_gsxgw.URL(string(_gsxv0))
			_gsxgw.S("\"")
			_gsxv1, _gsxerr := _gsxf0.IDTarget(ctx, (p.Results))
			if _gsxerr != nil {
				return _gsxerr
			}
			_gsxgw.S(" hx-target=\"")
			_gsxgw.AttrValue(string(_gsxv1))
			_gsxgw.S("\"")
			_gsxgw.S(" hx-swap=\"outerHTML\"")
			_gsxgw.S(" hx-trigger=\"input changed delay:250ms from:input, submit\"")
			_gsxgw.S(" hx-push-url=\"true\"")
			_gsxgw.S(">")
//line search.gsx:44:4
			_gsxgw.S("<input")
			_gsxgw.S(" name=\"q\"")
			_gsxgw.S(" value=\"")
			_gsxgw.AttrValue(string(props.Query))
			_gsxgw.S("\"")
			_gsxgw.S(" placeholder=\"Search posts...\"")
			_gsxgw.S(" class=\"w-full rounded border border-slate-300 px-3 py-2 text-sm\"")
			_gsxgw.BoolAttr("autofocus", true)
			_gsxgw.S("/>")
			_gsxgw.S("</form>")
//line search.gsx:52:3
			_gsxgw.Node(ctx, p.Results(props))
			return _gsxgw.Err()
		})}))
		return _gsxgw.Err()
	})
}

func (p searchPage) Results(props searchProps) gsx.Node {
	return gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
		_gsxgw := gsx.W(_gsxw)
//line search.gsx:57:2
		_gsxgw.S("<div")
		_gsxv2, _gsxerr := _gsxf0.ID(ctx, (searchPage.Results))
		if _gsxerr != nil {
			return _gsxerr
		}
		_gsxgw.S(" id=\"")
		_gsxgw.AttrValue(string(_gsxv2))
		_gsxgw.S("\"")
		_gsxgw.S(" class=\"space-y-4\"")
		_gsxgw.S(">")
//line search.gsx:58:3
		if props.Query == "" {
//line search.gsx:59:4
			_gsxgw.S("<p")
			_gsxgw.S(" class=\"text-sm text-slate-500\"")
			_gsxgw.S(">")
			_gsxgw.S("Type a query to search.")
			_gsxgw.S("</p>")
		} else {
//line search.gsx:60:10
			if len(props.Posts) == 0 {
//line search.gsx:61:4
				_gsxgw.S("<p")
				_gsxgw.S(" class=\"text-sm text-slate-500\"")
				_gsxgw.S(">")
				_gsxgw.S("No results for \"")
//line search.gsx:61:54
				_gsxgw.Text(string(props.Query))
				_gsxgw.S("\".")
				_gsxgw.S("</p>")
			} else {
//line search.gsx:63:4
				_gsxgw.S("<p")
				_gsxgw.S(" class=\"text-xs text-slate-500\"")
				_gsxgw.S(">")
//line search.gsx:63:38
				_gsxgw.Text(string(resultsCount(len(props.Posts))))
				_gsxgw.S("</p>")
//line search.gsx:64:4
				for _, post := range props.Posts {
//line search.gsx:65:5
					_gsxgw.Node(ctx, PostCard(PostCardProps{P: post}))
				}
			}
		}
		_gsxgw.S("</div>")
		return _gsxgw.Err()
	})
}
