// Code generated by gsx; DO NOT EDIT.

package components

import (
	"fmt"

	_gsxctx "context"
	"github.com/gsxhq/gsx"
	_gsxrt "github.com/gsxhq/gsx"
	_gsxio "io"
)

//line components.gsx:16:1
type AlertKind string

const (
	AlertInfo    AlertKind = "info"
	AlertError   AlertKind = "error"
	AlertSuccess AlertKind = "success"
)

func alertClasses(kind AlertKind) string {
	switch kind {
	case AlertError:
		return "border-red-200 bg-red-50 text-red-800"
	case AlertSuccess:
		return "border-emerald-200 bg-emerald-50 text-emerald-800"
	default:
		return "border-slate-200 bg-slate-50 text-slate-800"
	}
}

//line components.gsx:35:1
func Alert(kind AlertKind, msg string) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line components.gsx:36:2
		if msg != "" {
//line components.gsx:37:3
			_gsxgw.S("<div class=\"")
			_gsxgw.Class(_gsxrt.DefaultClassMerge, _gsxrt.Class("rounded border px-3 py-2 text-sm"), _gsxrt.Class(alertClasses(kind)))
			_gsxgw.S("\">")
//line components.gsx:38:4
			_gsxgw.Text(string(msg))
			_gsxgw.S("</div>")
		}
		return _gsxgw.Err()
	})
}

//line components.gsx:43:1
func Card(title string, children gsx.Node) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line components.gsx:44:2
		_gsxgw.S("<section class=\"rounded-lg border bg-white p-5 shadow-sm\">")
//line components.gsx:45:3
		if title != "" {
//line components.gsx:46:4
			_gsxgw.S("<h2 class=\"mb-3 text-base font-semibold text-slate-900\">")
//line components.gsx:47:5
			_gsxgw.Text(string(title))
			_gsxgw.S("</h2>")
		}
//line components.gsx:50:3
		_gsxgw.Node(ctx, children)
		_gsxgw.S("</section>")
		return _gsxgw.Err()
	})
}

//line components.gsx:54:1
// Button takes its label plus an attrs bag: unmatched call-site attributes
// (type, hx-*, etc.) collect in attrs and land on the root <button>.

//line components.gsx:56:1
func Button(label string, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line components.gsx:57:2
		_gsxgw.S("<button class=\"")
		_gsxgw.Class(_gsxrt.DefaultClassMerge, _gsxrt.Class("inline-flex items-center rounded bg-slate-900 px-3 py-1.5 text-sm font-medium text-white hover:bg-slate-700"), _gsxrt.Class(attrs.Class()))
		_gsxgw.S("\"")
		_gsxgw.StyleMerged("", attrs.Style())
		_gsxgw.Spread(ctx, "button", attrs, _gsxrt.AttrSinks{}, []string{"class", "style"})
		_gsxgw.S(">")
//line components.gsx:61:3
		_gsxgw.Text(string(label))
		_gsxgw.S("</button>")
		return _gsxgw.Err()
	})
}

//line components.gsx:65:1
func Input(name, label, value, errMsg string) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line components.gsx:66:2
		_gsxgw.S("<label class=\"block text-sm\">")
//line components.gsx:67:3
		_gsxgw.S("<span class=\"mb-1 block font-medium text-slate-700\">")
//line components.gsx:67:55
		_gsxgw.Text(string(label))
		_gsxgw.S("</span>")
//line components.gsx:68:3
		_gsxgw.S("<input name=\"")
		_gsxgw.AttrValue(string(name))
		_gsxgw.S("\" value=\"")
		_gsxgw.AttrValue(string(value))
		_gsxgw.S("\" class=\"")
		_gsxgw.Class(_gsxrt.DefaultClassMerge, _gsxrt.Class("w-full rounded border px-2 py-1.5 text-sm"), _gsxrt.ClassIf("border-slate-300", errMsg == ""), _gsxrt.ClassIf("border-red-400", errMsg != ""))
		_gsxgw.S("\">")
//line components.gsx:75:3
		if errMsg != "" {
//line components.gsx:76:4
			_gsxgw.S("<span class=\"mt-1 block text-xs text-red-600\">")
//line components.gsx:76:50
			_gsxgw.Text(string(errMsg))
			_gsxgw.S("</span>")
		}
		_gsxgw.S("</label>")
		return _gsxgw.Err()
	})
}

//line components.gsx:81:1
func Textarea(name, label, value, errMsg string) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line components.gsx:82:2
		_gsxgw.S("<label class=\"block text-sm\">")
//line components.gsx:83:3
		_gsxgw.S("<span class=\"mb-1 block font-medium text-slate-700\">")
//line components.gsx:83:55
		_gsxgw.Text(string(label))
		_gsxgw.S("</span>")
//line components.gsx:84:3
		_gsxgw.S("<textarea name=\"")
		_gsxgw.AttrValue(string(name))
		_gsxgw.S("\" rows=\"6\" class=\"")
		_gsxgw.Class(_gsxrt.DefaultClassMerge, _gsxrt.Class("w-full rounded border px-2 py-1.5 text-sm"), _gsxrt.ClassIf("border-slate-300", errMsg == ""), _gsxrt.ClassIf("border-red-400", errMsg != ""))
		_gsxgw.S("\">")
//line components.gsx:90:4
		_gsxgw.Text(string(value))
		_gsxgw.S("</textarea>")
//line components.gsx:91:3
		if errMsg != "" {
//line components.gsx:92:4
			_gsxgw.S("<span class=\"mt-1 block text-xs text-red-600\">")
//line components.gsx:92:50
			_gsxgw.Text(string(errMsg))
			_gsxgw.S("</span>")
		}
		_gsxgw.S("</label>")
		return _gsxgw.Err()
	})
}

// PageNav describes a paginated control. URL builds the link for a
// given page number; callers typically call structpages.URLFor with the
// "?page={page}" template form.
//
//line components.gsx:97:1
type PageNav struct {
	Page     int
	PageSize int
	Total    int
	URL      func(page int) (string, error)
}

func (p PageNav) Pages() int {
	if p.PageSize <= 0 {
		return 1
	}
	pages := p.Total / p.PageSize
	if p.Total%p.PageSize != 0 {
		pages++
	}
	if pages < 1 {
		pages = 1
	}
	return pages
}

func (p PageNav) Range() string {
	if p.Total == 0 {
		return "No results"
	}
	start := (p.Page-1)*p.PageSize + 1
	end := start + p.PageSize - 1
	if end > p.Total {
		end = p.Total
	}
	return fmt.Sprintf("%d–%d of %d", start, end, p.Total)
}

func (p PageNav) HasPrev() bool { return p.Page > 1 }
func (p PageNav) HasNext() bool { return p.Page < p.Pages() }

// Pagination is rendered as a standalone function component so HTMX requests
// with HX-Target: #pagination resolve here regardless of which page hosts it.

//line components.gsx:138:1
func Pagination(p PageNav) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
		var _gsxnum [32]byte
//line components.gsx:139:2
		_gsxgw.S("<nav id=\"pagination\" class=\"flex items-center justify-between text-sm\">")
//line components.gsx:140:3
		_gsxgw.S("<span class=\"text-slate-500\">")
//line components.gsx:140:32
		_gsxgw.Text(string(p.Range()))
		_gsxgw.S("</span>")
//line components.gsx:141:3
		_gsxgw.S("<div class=\"flex gap-2\">")
//line components.gsx:142:4
		_gsxgw.S("<a class=\"")
		_gsxgw.Class(_gsxrt.DefaultClassMerge, _gsxrt.Class("rounded border px-2 py-1"), _gsxrt.ClassIf("hover:bg-slate-50", p.HasPrev()), _gsxrt.ClassIf("text-slate-300", !p.HasPrev()))
		_gsxgw.S("\"")
		if p.HasPrev() {
			_gsxv0, _gsxerr := p.URL(p.Page - 1)
			if _gsxerr != nil {
				return _gsxerr
			}
			_gsxgw.S(" href=\"")
			_gsxgw.URL(string(_gsxv0))
			_gsxgw.S("\"")
		}
		_gsxgw.S(">← Prev</a>")
//line components.gsx:150:4
		_gsxgw.S("<span class=\"px-2 py-1 text-slate-600\">Page ")
//line components.gsx:151:10
		_gsxgw.IntInto(_gsxnum[:], int64(p.Page))
		_gsxgw.S(" of ")
//line components.gsx:151:24
		_gsxgw.IntInto(_gsxnum[:], int64(p.Pages()))
		_gsxgw.S("</span>")
//line components.gsx:153:4
		_gsxgw.S("<a class=\"")
		_gsxgw.Class(_gsxrt.DefaultClassMerge, _gsxrt.Class("rounded border px-2 py-1"), _gsxrt.ClassIf("hover:bg-slate-50", p.HasNext()), _gsxrt.ClassIf("text-slate-300", !p.HasNext()))
		_gsxgw.S("\"")
		if p.HasNext() {
			_gsxv1, _gsxerr := p.URL(p.Page + 1)
			if _gsxerr != nil {
				return _gsxerr
			}
			_gsxgw.S(" href=\"")
			_gsxgw.URL(string(_gsxv1))
			_gsxgw.S("\"")
		}
		_gsxgw.S(">Next →</a></div></nav>")
		return _gsxgw.Err()
	})
}

//line components.gsx:165:1
// ErrorPage is the full document rendered by main.errorHandler for non-HTMX
// errors. ErrorBlock is the partial used for HTMX requests.

//line components.gsx:167:1
func ErrorPage(status int, msg string) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
		var _gsxnum [32]byte
		_gsxgw.S("<!DOCTYPE html>")
//line components.gsx:169:2
		_gsxgw.S("<html lang=\"en\">")
//line components.gsx:170:3
		_gsxgw.S("<head>")
//line components.gsx:171:4
		_gsxgw.S("<meta charset=\"utf-8\">")
//line components.gsx:172:4
		_gsxgw.S("<title>Error ")
//line components.gsx:172:17
		_gsxgw.IntInto(_gsxnum[:], int64(status))
		_gsxgw.S("</title>")
//line components.gsx:173:4
		_gsxgw.S("<script src=\"https://cdn.tailwindcss.com\"")
		_gsxgw.Nonce(ctx)
		_gsxgw.S("></script></head>")
//line components.gsx:175:3
		_gsxgw.S("<body class=\"bg-slate-50 text-slate-900\">")
//line components.gsx:176:4
		_gsxgw.S("<main class=\"mx-auto max-w-md px-4 py-16\">")
//line components.gsx:177:5
		_gsxgw.NodeResult(_gsxrenderErrorBlock(ctx, _gsxgw, status, msg))
		_gsxgw.S("</main></body></html>")
		return _gsxgw.Err()
	})
}

//line components.gsx:183:1
func ErrorBlock(status int, msg string) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
		return _gsxrenderErrorBlock(ctx, _gsxgw, status, msg)
	})
}

func _gsxrenderErrorBlock(ctx _gsxctx.Context, _gsxgw *_gsxrt.Writer, status int, msg string) error {
	if _gsxerr := _gsxgw.Err(); _gsxerr != nil {
		return _gsxerr
	}
	var _gsxnum [32]byte
//line components.gsx:184:2
	_gsxgw.S("<div class=\"rounded-lg border border-red-200 bg-red-50 p-6 text-center\">")
//line components.gsx:185:3
	_gsxgw.S("<div class=\"text-4xl font-semibold text-red-700\">")
//line components.gsx:185:52
	_gsxgw.IntInto(_gsxnum[:], int64(status))
	_gsxgw.S("</div>")
//line components.gsx:186:3
	_gsxgw.S("<p class=\"mt-2 text-red-700\">")
//line components.gsx:186:32
	_gsxgw.Text(string(msg))
	_gsxgw.S("</p>")
//line components.gsx:187:3
	_gsxgw.S("<a class=\"mt-4 inline-block text-sm text-red-700 underline\" href=\"/\">Back to home</a></div>")
	return _gsxgw.Err()
}
