// Code generated by gsx; DO NOT EDIT.

package components

import (
	_gsxctx "context"
	_gsxio "io"

	_gsxrt "github.com/gsxhq/gsx"
)

type AlertKind string

const (
	AlertInfo    AlertKind = "info"
	AlertError   AlertKind = "error"
	AlertSuccess AlertKind = "success"
)

func alertClasses(kind AlertKind) string {
	switch kind {
	case AlertError:
		return "border-red-200 bg-red-50 text-red-800"
	case AlertSuccess:
		return "border-emerald-200 bg-emerald-50 text-emerald-800"
	default:
		return "border-slate-200 bg-slate-50 text-slate-800"
	}
}

type AlertProps struct {
	Kind AlertKind
	Msg  string
}

//line components.gsx:29:1
func Alert(_gsxp AlertProps) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		kind := _gsxp.Kind
		msg := _gsxp.Msg
		_gsxgw := _gsxrt.W(_gsxw)
//line components.gsx:30:2
		if msg != "" {
//line components.gsx:31:3
			_gsxgw.S("<div class=\"")
			_gsxgw.Class(_gsxrt.DefaultClassMerge, _gsxrt.Class("rounded border px-3 py-2 text-sm"), _gsxrt.Class(alertClasses(kind)))
			_gsxgw.S("\">")
//line components.gsx:32:4
			_gsxgw.Text(string(msg))
			_gsxgw.S("</div>")
		}
		return _gsxgw.Err()
	})
}

type CardProps struct {
	Title    string
	Children _gsxrt.Node
}

//line components.gsx:37:1
func Card(_gsxp CardProps) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		title := _gsxp.Title
		children := _gsxp.Children
		_gsxgw := _gsxrt.W(_gsxw)
//line components.gsx:38:2
		_gsxgw.S("<section class=\"rounded-lg border bg-white p-5 shadow-sm\">")
//line components.gsx:39:3
		if title != "" {
//line components.gsx:40:4
			_gsxgw.S("<h2 class=\"mb-3 text-base font-semibold text-slate-900\">")
//line components.gsx:41:5
			_gsxgw.Text(string(title))
			_gsxgw.S("</h2>")
		}
//line components.gsx:44:3
		_gsxgw.Node(ctx, children)
		_gsxgw.S("</section>")
		return _gsxgw.Err()
	})
}

// Button takes only its label. Spreading { attrs... } on the root <button>
// gives Button a synthesized Attrs prop: unmatched call-site attributes
// (type, hx-*, etc.) collect there and land on the <button>.

type ButtonProps struct {
	Label string
	Attrs _gsxrt.Attrs
}

//line components.gsx:51:1
func Button(_gsxp ButtonProps) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		label := _gsxp.Label
		attrs := _gsxp.Attrs
		_gsxgw := _gsxrt.W(_gsxw)
//line components.gsx:52:2
		_gsxgw.S("<button class=\"")
		_gsxgw.Class(_gsxrt.DefaultClassMerge, _gsxrt.Class("inline-flex items-center rounded bg-slate-900 px-3 py-1.5 text-sm font-medium text-white hover:bg-slate-700"), _gsxrt.Class(attrs.Class()))
		_gsxgw.S("\"")
		_gsxgw.StyleMerged("", attrs.Style())
		_gsxgw.Spread(ctx, attrs.Without("class", "style"))
		_gsxgw.S(">")
//line components.gsx:56:3
		_gsxgw.Text(string(label))
		_gsxgw.S("</button>")
		return _gsxgw.Err()
	})
}

type InputProps struct {
	Name   string
	Label  string
	Value  string
	ErrMsg string
}

//line components.gsx:60:1
func Input(_gsxp InputProps) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		name := _gsxp.Name
		label := _gsxp.Label
		value := _gsxp.Value
		errMsg := _gsxp.ErrMsg
		_gsxgw := _gsxrt.W(_gsxw)
//line components.gsx:61:2
		_gsxgw.S("<label class=\"block text-sm\">")
//line components.gsx:62:3
		_gsxgw.S("<span class=\"mb-1 block font-medium text-slate-700\">")
//line components.gsx:62:55
		_gsxgw.Text(string(label))
		_gsxgw.S("</span>")
//line components.gsx:63:3
		_gsxgw.S("<input name=\"")
		_gsxgw.AttrValue(string(name))
		_gsxgw.S("\" value=\"")
		_gsxgw.AttrValue(string(value))
		_gsxgw.S("\" class=\"")
		_gsxgw.Class(_gsxrt.DefaultClassMerge, _gsxrt.Class("w-full rounded border px-2 py-1.5 text-sm"), _gsxrt.ClassIf("border-slate-300", errMsg == ""), _gsxrt.ClassIf("border-red-400", errMsg != ""))
		_gsxgw.S("\"/>")
//line components.gsx:70:3
		if errMsg != "" {
//line components.gsx:71:4
			_gsxgw.S("<span class=\"mt-1 block text-xs text-red-600\">")
//line components.gsx:71:50
			_gsxgw.Text(string(errMsg))
			_gsxgw.S("</span>")
		}
		_gsxgw.S("</label>")
		return _gsxgw.Err()
	})
}

type TextareaProps struct {
	Name   string
	Label  string
	Value  string
	ErrMsg string
}

//line components.gsx:76:1
func Textarea(_gsxp TextareaProps) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		name := _gsxp.Name
		label := _gsxp.Label
		value := _gsxp.Value
		errMsg := _gsxp.ErrMsg
		_gsxgw := _gsxrt.W(_gsxw)
//line components.gsx:77:2
		_gsxgw.S("<label class=\"block text-sm\">")
//line components.gsx:78:3
		_gsxgw.S("<span class=\"mb-1 block font-medium text-slate-700\">")
//line components.gsx:78:55
		_gsxgw.Text(string(label))
		_gsxgw.S("</span>")
//line components.gsx:79:3
		_gsxgw.S("<textarea name=\"")
		_gsxgw.AttrValue(string(name))
		_gsxgw.S("\" rows=\"6\" class=\"")
		_gsxgw.Class(_gsxrt.DefaultClassMerge, _gsxrt.Class("w-full rounded border px-2 py-1.5 text-sm"), _gsxrt.ClassIf("border-slate-300", errMsg == ""), _gsxrt.ClassIf("border-red-400", errMsg != ""))
		_gsxgw.S("\">")
//line components.gsx:85:4
		_gsxgw.Text(string(value))
		_gsxgw.S("</textarea>")
//line components.gsx:86:3
		if errMsg != "" {
//line components.gsx:87:4
			_gsxgw.S("<span class=\"mt-1 block text-xs text-red-600\">")
//line components.gsx:87:50
			_gsxgw.Text(string(errMsg))
			_gsxgw.S("</span>")
		}
		_gsxgw.S("</label>")
		return _gsxgw.Err()
	})
}

// Pagination is rendered as a standalone function component so HTMX requests
// with HX-Target: #pagination resolve here regardless of which page hosts it.

//line components.gsx:94:1
func Pagination(p PageNav) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
		var _gsxnum [32]byte
//line components.gsx:95:2
		_gsxgw.S("<nav id=\"pagination\" class=\"flex items-center justify-between text-sm\">")
//line components.gsx:96:3
		_gsxgw.S("<span class=\"text-slate-500\">")
//line components.gsx:96:32
		_gsxgw.Text(string(p.Range()))
		_gsxgw.S("</span>")
//line components.gsx:97:3
		_gsxgw.S("<div class=\"flex gap-2\">")
//line components.gsx:98:4
		if p.HasPrev() {
//line components.gsx:99:5
			_gsxgw.S("<a class=\"rounded border px-2 py-1 hover:bg-slate-50\"")
			_gsxv0, _gsxerr := p.URL(p.Page - 1)
			if _gsxerr != nil {
				return _gsxerr
			}
			_gsxgw.S(" href=\"")
			_gsxgw.URL(string(_gsxv0))
			_gsxgw.S("\">← Prev</a>")
		} else {
//line components.gsx:106:5
			_gsxgw.S("<span class=\"rounded border px-2 py-1 text-slate-300\">← Prev</span>")
		}
//line components.gsx:110:4
		_gsxgw.S("<span class=\"px-2 py-1 text-slate-600\">Page ")
//line components.gsx:111:10
		_gsxgw.IntInto(_gsxnum[:], int64(p.Page))
		_gsxgw.S(" of ")
//line components.gsx:111:24
		_gsxgw.IntInto(_gsxnum[:], int64(p.Pages()))
		_gsxgw.S("</span>")
//line components.gsx:113:4
		if p.HasNext() {
//line components.gsx:114:5
			_gsxgw.S("<a class=\"rounded border px-2 py-1 hover:bg-slate-50\"")
			_gsxv1, _gsxerr := p.URL(p.Page + 1)
			if _gsxerr != nil {
				return _gsxerr
			}
			_gsxgw.S(" href=\"")
			_gsxgw.URL(string(_gsxv1))
			_gsxgw.S("\">Next →</a>")
		} else {
//line components.gsx:121:5
			_gsxgw.S("<span class=\"rounded border px-2 py-1 text-slate-300\">Next →</span>")
		}
		_gsxgw.S("</div></nav>")
		return _gsxgw.Err()
	})
}

// ErrorPage is the full document rendered by main.errorHandler for non-HTMX
// errors. ErrorBlock is the partial used for HTMX requests.

type ErrorPageProps struct {
	Status int
	Msg    string
}

//line components.gsx:131:1
func ErrorPage(_gsxp ErrorPageProps) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		status := _gsxp.Status
		msg := _gsxp.Msg
		_gsxgw := _gsxrt.W(_gsxw)
		var _gsxnum [32]byte
		_gsxgw.S("<!DOCTYPE html>")
//line components.gsx:133:2
		_gsxgw.S("<html lang=\"en\">")
//line components.gsx:134:3
		_gsxgw.S("<head>")
//line components.gsx:135:4
		_gsxgw.S("<meta charset=\"utf-8\"/>")
//line components.gsx:136:4
		_gsxgw.S("<title>Error ")
//line components.gsx:136:17
		_gsxgw.IntInto(_gsxnum[:], int64(status))
		_gsxgw.S("</title>")
//line components.gsx:137:4
		_gsxgw.S("<script src=\"https://cdn.tailwindcss.com\"")
		_gsxgw.Nonce(ctx)
		_gsxgw.S("></script></head>")
//line components.gsx:139:3
		_gsxgw.S("<body class=\"bg-slate-50 text-slate-900\">")
//line components.gsx:140:4
		_gsxgw.S("<main class=\"mx-auto max-w-md px-4 py-16\">")
//line components.gsx:141:5
		_gsxgw.Node(ctx, ErrorBlock(ErrorBlockProps{Status: status, Msg: msg}))
		_gsxgw.S("</main></body></html>")
		return _gsxgw.Err()
	})
}

type ErrorBlockProps struct {
	Status int
	Msg    string
}

//line components.gsx:147:1
func ErrorBlock(_gsxp ErrorBlockProps) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		status := _gsxp.Status
		msg := _gsxp.Msg
		_gsxgw := _gsxrt.W(_gsxw)
		var _gsxnum [32]byte
//line components.gsx:148:2
		_gsxgw.S("<div class=\"rounded-lg border border-red-200 bg-red-50 p-6 text-center\">")
//line components.gsx:149:3
		_gsxgw.S("<div class=\"text-4xl font-semibold text-red-700\">")
//line components.gsx:149:52
		_gsxgw.IntInto(_gsxnum[:], int64(status))
		_gsxgw.S("</div>")
//line components.gsx:150:3
		_gsxgw.S("<p class=\"mt-2 text-red-700\">")
//line components.gsx:150:32
		_gsxgw.Text(string(msg))
		_gsxgw.S("</p>")
//line components.gsx:151:3
		_gsxgw.S("<a class=\"mt-4 inline-block text-sm text-red-700 underline\" href=\"/\">Back to home</a></div>")
		return _gsxgw.Err()
	})
}
