// Code generated by gsx; DO NOT EDIT.

package main

import (
	"context"
	"fmt"
	"io"

	"github.com/gsxhq/gsx"
	_gsxf0 "github.com/jackielii/structpages"
)

// Shared standalone function components (can be used across multiple pages).
// These demonstrate the power of RenderTarget — no wrapper methods needed.

func UserStatsWidget(stats UserStats) gsx.Node {
	return gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
		_gsxgw := gsx.W(_gsxw)
//line pages.gsx:11:2
		_gsxgw.S("<div")
		_gsxgw.S(" class=\"widget\"")
		_gsxgw.S(">")
//line pages.gsx:12:3
		_gsxgw.S("<h3")
		_gsxgw.S(">")
		_gsxgw.S("User Statistics")
		_gsxgw.S("</h3>")
//line pages.gsx:13:3
		_gsxgw.S("<p")
		_gsxgw.S(">")
		_gsxgw.S("Active Users: ")
//line pages.gsx:13:20
		_gsxgw.Text(string(fmt.Sprintf("%d", stats.ActiveUsers)))
		_gsxgw.S("</p>")
//line pages.gsx:14:3
		_gsxgw.S("<p")
		_gsxgw.S(">")
		_gsxgw.S("New Today: ")
//line pages.gsx:14:17
		_gsxgw.Text(string(fmt.Sprintf("%d", stats.NewToday)))
		_gsxgw.S("</p>")
//line pages.gsx:15:3
		_gsxgw.S("<button")
		_gsxgw.S(" type=\"button\"")
		_gsxv0, _gsxerr := _gsxf0.URLFor(ctx, (dashboard{}))
		if _gsxerr != nil {
			return _gsxerr
		}
		_gsxgw.S(" hx-get=\"")
		_gsxgw.URL(string(_gsxv0))
		_gsxgw.S("\"")
		_gsxv1, _gsxerr := _gsxf0.IDTarget(ctx, (UserStatsWidget))
		if _gsxerr != nil {
			return _gsxerr
		}
		_gsxgw.S(" hx-target=\"")
		_gsxgw.AttrValue(string(_gsxv1))
		_gsxgw.S("\"")
		_gsxgw.S(">")
		_gsxgw.S("Refresh Stats")
		_gsxgw.S("</button>")
		_gsxgw.S("</div>")
		return _gsxgw.Err()
	})
}

func SalesChartWidget(data SalesData) gsx.Node {
	return gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
		_gsxgw := gsx.W(_gsxw)
//line pages.gsx:24:2
		_gsxgw.S("<div")
		_gsxgw.S(" class=\"widget\"")
		_gsxgw.S(">")
//line pages.gsx:25:3
		_gsxgw.S("<h3")
		_gsxgw.S(">")
		_gsxgw.S("Sales Chart")
		_gsxgw.S("</h3>")
//line pages.gsx:26:3
		_gsxgw.S("<div")
		_gsxgw.S(" class=\"chart\"")
		_gsxgw.S(">")
//line pages.gsx:27:4
		for _, point := range data.Points {
//line pages.gsx:28:5
			_gsxgw.S("<div")
			_gsxgw.S(" class=\"bar\"")
			_gsxgw.S(" data-h=\"")
			_gsxgw.AttrValue(string(fmt.Sprint(point.Value)))
			_gsxgw.S("\"")
			_gsxgw.S(" style=\"width: 30px; background: blue; display: inline-block; margin: 2px;\"")
			_gsxgw.S(">")
			_gsxgw.S("</div>")
		}
		_gsxgw.S("</div>")
//line pages.gsx:31:3
		_gsxgw.S("<p")
		_gsxgw.S(">")
		_gsxgw.S("Total Sales: $")
//line pages.gsx:31:20
		_gsxgw.Text(string(fmt.Sprintf("%.2f", data.Total)))
		_gsxgw.S("</p>")
//line pages.gsx:32:3
		_gsxgw.S("<button")
		_gsxgw.S(" type=\"button\"")
		_gsxv2, _gsxerr := _gsxf0.URLFor(ctx, (dashboard{}))
		if _gsxerr != nil {
			return _gsxerr
		}
		_gsxgw.S(" hx-get=\"")
		_gsxgw.URL(string(_gsxv2))
		_gsxgw.S("\"")
		_gsxv3, _gsxerr := _gsxf0.IDTarget(ctx, (SalesChartWidget))
		if _gsxerr != nil {
			return _gsxerr
		}
		_gsxgw.S(" hx-target=\"")
		_gsxgw.AttrValue(string(_gsxv3))
		_gsxgw.S("\"")
		_gsxgw.S(">")
		_gsxgw.S("Refresh Sales")
		_gsxgw.S("</button>")
		_gsxgw.S("</div>")
		return _gsxgw.Err()
	})
}

type NotificationsListProps struct {
	Notifications []Notification
	Attrs         gsx.Attrs
}

func NotificationsList(_gsxp NotificationsListProps) gsx.Node {
	return gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
		notifications := _gsxp.Notifications
		_gsxgw := gsx.W(_gsxw)
//line pages.gsx:41:2
		_gsxgw.S("<div")
		_gsxgw.S(" class=\"")
		_gsxgw.Class(gsx.Class("widget"), gsx.Class(_gsxp.Attrs.Class()))
		_gsxgw.S("\"")
		_gsxgw.StyleMerged("", _gsxp.Attrs.Style())
		_gsxgw.Spread(ctx, _gsxp.Attrs.Without("class", "style"))
		_gsxgw.S(">")
//line pages.gsx:42:3
		_gsxgw.S("<h3")
		_gsxgw.S(">")
		_gsxgw.S("Recent Notifications")
		_gsxgw.S("</h3>")
//line pages.gsx:43:3
		_gsxgw.S("<ul")
		_gsxgw.S(">")
//line pages.gsx:44:4
		for _, n := range notifications {
//line pages.gsx:45:5
			_gsxgw.S("<li")
			_gsxgw.S(">")
//line pages.gsx:45:9
			_gsxgw.Text(string(n.Message))
			_gsxgw.S(" ")
//line pages.gsx:45:23
			_gsxgw.S("<small")
			_gsxgw.S(">")
			_gsxgw.S("(")
//line pages.gsx:45:31
			_gsxgw.Text(string(n.Time.Format("15:04")))
			_gsxgw.S(")")
			_gsxgw.S("</small>")
			_gsxgw.S("</li>")
		}
		_gsxgw.S("</ul>")
//line pages.gsx:48:3
		_gsxgw.S("<button")
		_gsxgw.S(" type=\"button\"")
		_gsxv4, _gsxerr := _gsxf0.URLFor(ctx, (dashboard{}))
		if _gsxerr != nil {
			return _gsxerr
		}
		_gsxgw.S(" hx-get=\"")
		_gsxgw.URL(string(_gsxv4))
		_gsxgw.S("\"")
		_gsxv5, _gsxerr := _gsxf0.IDTarget(ctx, (NotificationsList))
		if _gsxerr != nil {
			return _gsxerr
		}
		_gsxgw.S(" hx-target=\"")
		_gsxgw.AttrValue(string(_gsxv5))
		_gsxgw.S("\"")
		_gsxgw.S(">")
		_gsxgw.S("Refresh Notifications")
		_gsxgw.S("</button>")
		_gsxgw.S("</div>")
		return _gsxgw.Err()
	})
}

// Dashboard page.

type dashboard struct{}

func (p dashboard) Page(props dashboardData) gsx.Node {
	return gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
		_gsxgw := gsx.W(_gsxw)
//line pages.gsx:61:2
		_gsxgw.Node(ctx, Html(HtmlProps{Children: gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
			_gsxgw := gsx.W(_gsxw)
//line pages.gsx:62:3
			_gsxgw.S("<h1")
			_gsxgw.S(">")
			_gsxgw.S("Dashboard")
			_gsxgw.S("</h1>")
//line pages.gsx:63:3
			_gsxgw.S("<p")
			_gsxgw.S(">")
			_gsxgw.S("This example demonstrates the RenderTarget API with standalone function components.")
			_gsxgw.S("</p>")
//line pages.gsx:64:3
			_gsxgw.S("<p")
			_gsxgw.S(">")
			_gsxgw.S("Click \"Refresh\" buttons to see HTMX partial updates — each widget loads only its own data!")
			_gsxgw.S("</p>")
//line pages.gsx:65:3
			_gsxgw.S("<div")
			_gsxgw.S(" style=\"display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 1rem; margin-top: 2rem;\"")
			_gsxgw.S(">")
//line pages.gsx:66:4
			_gsxgw.S("<div")
			_gsxv6, _gsxerr := _gsxf0.ID(ctx, (UserStatsWidget))
			if _gsxerr != nil {
				return _gsxerr
			}
			_gsxgw.S(" id=\"")
			_gsxgw.AttrValue(string(_gsxv6))
			_gsxgw.S("\"")
			_gsxgw.S(">")
//line pages.gsx:67:5
			_gsxgw.Node(ctx, UserStatsWidget(props.Stats))
			_gsxgw.S("</div>")
//line pages.gsx:69:4
			_gsxgw.S("<div")
			_gsxv7, _gsxerr := _gsxf0.ID(ctx, (SalesChartWidget))
			if _gsxerr != nil {
				return _gsxerr
			}
			_gsxgw.S(" id=\"")
			_gsxgw.AttrValue(string(_gsxv7))
			_gsxgw.S("\"")
			_gsxgw.S(">")
//line pages.gsx:70:5
			_gsxgw.Node(ctx, SalesChartWidget(props.Sales))
			_gsxgw.S("</div>")
//line pages.gsx:72:4
			_gsxgw.S("<div")
			_gsxv8, _gsxerr := _gsxf0.ID(ctx, (NotificationsList))
			if _gsxerr != nil {
				return _gsxerr
			}
			_gsxgw.S(" id=\"")
			_gsxgw.AttrValue(string(_gsxv8))
			_gsxgw.S("\"")
			_gsxgw.S(">")
//line pages.gsx:73:5
			_gsxgw.Node(ctx, NotificationsList(NotificationsListProps{Notifications: props.Notifications}))
			_gsxgw.S("</div>")
			_gsxgw.S("</div>")
//line pages.gsx:76:3
			_gsxgw.S("<div")
			_gsxgw.S(" style=\"margin-top: 2rem; padding: 1rem; background: #f0f0f0; border-radius: 4px;\"")
			_gsxgw.S(">")
//line pages.gsx:77:4
			_gsxgw.S("<h4")
			_gsxgw.S(">")
			_gsxgw.S("How it works:")
			_gsxgw.S("</h4>")
//line pages.gsx:78:4
			_gsxgw.S("<ul")
			_gsxgw.S(">")
//line pages.gsx:79:5
			_gsxgw.S("<li")
			_gsxgw.S(">")
			_gsxgw.S("✅ ")
//line pages.gsx:79:13
			_gsxgw.S("<strong")
			_gsxgw.S(">")
			_gsxgw.S("Standalone functions")
			_gsxgw.S("</strong>")
			_gsxgw.S(" — UserStatsWidget, SalesChartWidget, NotificationsList are shared components")
			_gsxgw.S("</li>")
//line pages.gsx:80:5
			_gsxgw.S("<li")
			_gsxgw.S(">")
			_gsxgw.S("✅ ")
//line pages.gsx:80:13
			_gsxgw.S("<strong")
			_gsxgw.S(">")
			_gsxgw.S("Conditional loading")
			_gsxgw.S("</strong>")
			_gsxgw.S(" — Props checks target.Is() and loads only needed data")
			_gsxgw.S("</li>")
//line pages.gsx:81:5
			_gsxgw.S("<li")
			_gsxgw.S(">")
			_gsxgw.S("✅ ")
//line pages.gsx:81:13
			_gsxgw.S("<strong")
			_gsxgw.S(">")
			_gsxgw.S("RenderComponent (direct)")
			_gsxgw.S("</strong>")
			_gsxgw.S(" — construct the gsx component with its props struct and pass directly")
			_gsxgw.S("</li>")
//line pages.gsx:82:5
			_gsxgw.S("<li")
			_gsxgw.S(">")
			_gsxgw.S("✅ ")
//line pages.gsx:82:13
			_gsxgw.S("<strong")
			_gsxgw.S(">")
			_gsxgw.S("No wrapper methods")
			_gsxgw.S("</strong>")
			_gsxgw.S(" — No need to create dashboard.UserStats() method!")
			_gsxgw.S("</li>")
//line pages.gsx:83:5
			_gsxgw.S("<li")
			_gsxgw.S(">")
			_gsxgw.S("✅ ")
//line pages.gsx:83:13
			_gsxgw.S("<strong")
			_gsxgw.S(">")
			_gsxgw.S("HTMX integration")
			_gsxgw.S("</strong>")
			_gsxgw.S(" — HTMXRenderTarget automatically handles partial updates")
			_gsxgw.S("</li>")
			_gsxgw.S("</ul>")
			_gsxgw.S("</div>")
			return _gsxgw.Err()
		})}))
		return _gsxgw.Err()
	})
}

// Html is the full-page layout.

type HtmlProps struct {
	Children gsx.Node
}

func Html(_gsxp HtmlProps) gsx.Node {
	return gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
		children := _gsxp.Children
		_gsxgw := gsx.W(_gsxw)
		_gsxgw.S("<!DOCTYPE html>")
//line pages.gsx:92:2
		_gsxgw.S("<html")
		_gsxgw.S(" lang=\"en\"")
		_gsxgw.S(">")
//line pages.gsx:93:3
		_gsxgw.S("<head")
		_gsxgw.S(">")
//line pages.gsx:94:4
		_gsxgw.S("<link")
		_gsxgw.S(" rel=\"stylesheet\"")
		_gsxgw.S(" href=\"https://unpkg.com/missing.css@1.1.3\"")
		_gsxgw.S("/>")
//line pages.gsx:95:4
		_gsxgw.S("<script")
		_gsxgw.S(" src=\"https://unpkg.com/htmx.org@2.0.4\"")
		_gsxgw.S(">")
		_gsxgw.S("</script>")
//line pages.gsx:96:4
		_gsxgw.S("<title")
		_gsxgw.S(">")
		_gsxgw.S("RenderTarget API Example")
		_gsxgw.S("</title>")
//line pages.gsx:97:4
		_gsxgw.S("<style")
		_gsxgw.S(">")
		_gsxgw.S(".widget{padding: 1rem;border: 1px solid #ddd;border-radius: 8px;background: white}.widget h3{margin-top: 0}.chart{display: flex;align-items: flex-end;height: 150px;margin: 1rem 0}")
		_gsxgw.S("</style>")
		_gsxgw.S("</head>")
//line pages.gsx:115:3
		_gsxgw.S("<body")
		_gsxgw.S(">")
//line pages.gsx:116:4
		_gsxgw.S("<main")
		_gsxgw.S(">")
//line pages.gsx:117:5
		_gsxgw.Node(ctx, children)
		_gsxgw.S("</main>")
		_gsxgw.S("</body>")
		_gsxgw.S("</html>")
		return _gsxgw.Err()
	})
}

type ErrorPageProps struct {
	Err error
}

func ErrorPage(_gsxp ErrorPageProps) gsx.Node {
	return gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
		err := _gsxp.Err
		_gsxgw := gsx.W(_gsxw)
//line pages.gsx:124:2
		_gsxgw.Node(ctx, Html(HtmlProps{Children: gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
			_gsxgw := gsx.W(_gsxw)
//line pages.gsx:125:3
			_gsxgw.Node(ctx, ErrorComp(ErrorCompProps{Err: err}))
			return _gsxgw.Err()
		})}))
		return _gsxgw.Err()
	})
}

type ErrorCompProps struct {
	Err error
}

func ErrorComp(_gsxp ErrorCompProps) gsx.Node {
	return gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
		err := _gsxp.Err
		_gsxgw := gsx.W(_gsxw)
//line pages.gsx:130:2
		_gsxgw.S("<h1")
		_gsxgw.S(">")
		_gsxgw.S("Error")
		_gsxgw.S("</h1>")
//line pages.gsx:131:2
		_gsxgw.S("<p")
		_gsxgw.S(">")
//line pages.gsx:131:5
		_gsxgw.Text(string(err.Error()))
		_gsxgw.S("</p>")
		return _gsxgw.Err()
	})
}
