// Code generated by gsx; DO NOT EDIT.

package main

import (
	"context"
	"io"
	"net/http"
	"strconv"

	"github.com/gsxhq/gsx"
	"github.com/jackielii/structpages"
	_gsxf0 "github.com/jackielii/structpages"
)

type index struct {
	add        `route:"POST /add AddTodo" form:"text"`
	toggle     `route:"POST /toggle/{id} ToggleTodo"`
	deleteTodo `route:"DELETE /delete/{id} DeleteTodo"`
}

func (p index) Page() gsx.Node {
	return gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
		_gsxgw := gsx.W(_gsxw)
//line pages.gsx:17:2
		_gsxgw.Node(ctx, Layout(LayoutProps{Children: gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
			_gsxgw := gsx.W(_gsxw)
//line pages.gsx:18:3
			_gsxgw.S("<div")
			_gsxgw.S(" class=\"todo-app\"")
			_gsxgw.S(">")
//line pages.gsx:19:4
			_gsxgw.S("<h1")
			_gsxgw.S(">")
			_gsxgw.S("TODO App")
			_gsxgw.S("</h1>")
//line pages.gsx:20:4
			_gsxgw.S("<form")
			_gsxv0, _gsxerr := _gsxf0.URLFor(ctx, (add{}))
			if _gsxerr != nil {
				return _gsxerr
			}
			_gsxgw.S(" hx-post=\"")
			_gsxgw.URL(string(_gsxv0))
			_gsxgw.S("\"")
			_gsxv1, _gsxerr := _gsxf0.IDTarget(ctx, (index.TodoList))
			if _gsxerr != nil {
				return _gsxerr
			}
			_gsxgw.S(" hx-target=\"")
			_gsxgw.AttrValue(string(_gsxv1))
			_gsxgw.S("\"")
			_gsxgw.S(" hx-swap=\"innerHTML\"")
			_gsxgw.S(" hx-on:htmx:after-request=\"this.reset()\"")
			_gsxgw.S(">")
//line pages.gsx:26:5
			_gsxgw.S("<div")
			_gsxgw.S(" class=\"form-group\"")
			_gsxgw.S(">")
//line pages.gsx:27:6
			_gsxgw.S("<input")
			_gsxgw.S(" type=\"text\"")
			_gsxgw.S(" name=\"text\"")
			_gsxgw.S(" placeholder=\"Add a new todo...\"")
			_gsxgw.BoolAttr("required", true)
			_gsxgw.S("/>")
//line pages.gsx:33:6
			_gsxgw.S("<button")
			_gsxgw.S(" type=\"submit\"")
			_gsxgw.S(">")
			_gsxgw.S("Add Todo")
			_gsxgw.S("</button>")
			_gsxgw.S("</div>")
			_gsxgw.S("</form>")
//line pages.gsx:36:4
			_gsxgw.S("<div")
			_gsxv2, _gsxerr := _gsxf0.ID(ctx, (index.TodoList))
			if _gsxerr != nil {
				return _gsxerr
			}
			_gsxgw.S(" id=\"")
			_gsxgw.AttrValue(string(_gsxv2))
			_gsxgw.S("\"")
			_gsxgw.S(">")
//line pages.gsx:37:5
			_gsxgw.Node(ctx, p.TodoList())
			_gsxgw.S("</div>")
			_gsxgw.S("</div>")
			return _gsxgw.Err()
		})}))
		return _gsxgw.Err()
	})
}

func (p index) TodoList() gsx.Node {
	return gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
		_gsxgw := gsx.W(_gsxw)
//line pages.gsx:44:2
		_gsxgw.Node(ctx, TodoList())
		return _gsxgw.Err()
	})
}

type add struct{}

func (a add) ServeHTTP(w http.ResponseWriter, r *http.Request) error {
	if r.Method == "POST" {
		text := r.FormValue("text")
		if text != "" {
			addTodo(text)
		}
	}
	return structpages.RenderComponent(index.TodoList)
}

type toggle struct{}

func (t toggle) ServeHTTP(w http.ResponseWriter, r *http.Request) error {
	id, err := strconv.Atoi(r.PathValue("id"))
	if err != nil {
		return err
	}
	if r.Method == "POST" {
		toggleTodo(id)
	}
	return structpages.RenderComponent(index.TodoList)
}

type deleteTodo struct{}

func (d deleteTodo) ServeHTTP(w http.ResponseWriter, r *http.Request) error {
	id, err := strconv.Atoi(r.PathValue("id"))
	if err != nil {
		return err
	}
	if r.Method == "DELETE" {
		removeTodo(id)
	}
	return structpages.RenderComponent(index.TodoList)
}

func TodoList() gsx.Node {
	return gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
		_gsxgw := gsx.W(_gsxw)
//line pages.gsx:86:2
		_gsxgw.S("<ul")
		_gsxgw.S(" class=\"todo-list\"")
		_gsxgw.S(">")
//line pages.gsx:87:3
		for _, todo := range getTodos() {
//line pages.gsx:88:4
			_gsxgw.S("<li")
			_gsxgw.S(" class=\"")
			_gsxgw.Class(gsx.Class("todo-item"), gsx.ClassIf("completed", todo.Completed))
			_gsxgw.S("\"")
			_gsxgw.S(">")
//line pages.gsx:89:5
			_gsxgw.S("<div")
			_gsxgw.S(" class=\"todo-content\"")
			_gsxgw.S(">")
//line pages.gsx:90:6
			_gsxgw.S("<input")
			_gsxgw.S(" type=\"checkbox\"")
			_gsxgw.BoolAttr("checked", bool(todo.Completed))
			_gsxv3, _gsxerr := _gsxf0.URLFor(ctx, (toggle{}), "id", todo.ID)
			if _gsxerr != nil {
				return _gsxerr
			}
			_gsxgw.S(" hx-post=\"")
			_gsxgw.URL(string(_gsxv3))
			_gsxgw.S("\"")
			_gsxv4, _gsxerr := _gsxf0.IDTarget(ctx, (index.TodoList))
			if _gsxerr != nil {
				return _gsxerr
			}
			_gsxgw.S(" hx-target=\"")
			_gsxgw.AttrValue(string(_gsxv4))
			_gsxgw.S("\"")
			_gsxgw.S(" hx-swap=\"innerHTML\"")
			_gsxgw.S("/>")
//line pages.gsx:97:6
			_gsxgw.S("<span")
			_gsxgw.S(" class=\"todo-text\"")
			_gsxgw.S(">")
//line pages.gsx:97:30
			_gsxgw.Text(string(todo.Text))
			_gsxgw.S("</span>")
			_gsxgw.S("</div>")
//line pages.gsx:99:5
			_gsxgw.S("<button")
			_gsxgw.S(" class=\"delete-btn\"")
			_gsxv5, _gsxerr := _gsxf0.URLFor(ctx, (deleteTodo{}), "id", todo.ID)
			if _gsxerr != nil {
				return _gsxerr
			}
			_gsxgw.S(" hx-delete=\"")
			_gsxgw.URL(string(_gsxv5))
			_gsxgw.S("\"")
			_gsxv6, _gsxerr := _gsxf0.IDTarget(ctx, (index.TodoList))
			if _gsxerr != nil {
				return _gsxerr
			}
			_gsxgw.S(" hx-target=\"")
			_gsxgw.AttrValue(string(_gsxv6))
			_gsxgw.S("\"")
			_gsxgw.S(" hx-swap=\"innerHTML\"")
			_gsxgw.S(" hx-confirm=\"Are you sure you want to delete this todo?\"")
			_gsxgw.S(">")
			_gsxgw.S("×")
			_gsxgw.S("</button>")
			_gsxgw.S("</li>")
		}
		_gsxgw.S("</ul>")
//line pages.gsx:111:2
		if len(getTodos()) == 0 {
//line pages.gsx:112:3
			_gsxgw.S("<p")
			_gsxgw.S(" class=\"empty-state\"")
			_gsxgw.S(">")
			_gsxgw.S("No todos yet. Add one above!")
			_gsxgw.S("</p>")
		}
		return _gsxgw.Err()
	})
}

type LayoutProps struct {
	Children gsx.Node
}

func Layout(_gsxp LayoutProps) gsx.Node {
	return gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
		children := _gsxp.Children
		_gsxgw := gsx.W(_gsxw)
		_gsxgw.S("<!DOCTYPE html>")
//line pages.gsx:118:2
		_gsxgw.S("<html")
		_gsxgw.S(" lang=\"en\"")
		_gsxgw.S(">")
//line pages.gsx:119:3
		_gsxgw.S("<head")
		_gsxgw.S(">")
//line pages.gsx:120:4
		_gsxgw.S("<link")
		_gsxgw.S(" rel=\"stylesheet\"")
		_gsxgw.S(" href=\"https://unpkg.com/missing.css@1.1.3\"")
		_gsxgw.S("/>")
//line pages.gsx:121:4
		_gsxgw.S("<script")
		_gsxgw.S(" src=\"https://unpkg.com/htmx.org@2.0.4\"")
		_gsxgw.S(">")
		_gsxgw.S("</script>")
//line pages.gsx:122:4
		_gsxgw.S("<title")
		_gsxgw.S(">")
		_gsxgw.S("TODO App")
		_gsxgw.S("</title>")
//line pages.gsx:123:4
		_gsxgw.S("<style")
		_gsxgw.S(">")
		_gsxgw.S(".todo-app{max-width: 600px;margin: 2rem auto;padding: 2rem}.form-group{display: flex;gap: 0.5rem;margin-bottom: 2rem}.form-group input{flex: 1;padding: 0.75rem;border: 1px solid #ddd;border-radius: 4px}.form-group button{padding: 0.75rem 1.5rem;background: #007bff;color: white;border: none;border-radius: 4px;cursor: pointer}.form-group button:hover{background: #0056b3}.todo-list{list-style: none;padding: 0}.todo-item{display: flex;align-items: center;justify-content: space-between;padding: 1rem;border: 1px solid #eee;border-radius: 4px;margin-bottom: 0.5rem;background: white}.todo-item.completed{opacity: 0.6}.todo-item.completed .todo-text{text-decoration: line-through}.todo-content{display: flex;align-items: center;gap: 0.75rem;flex: 1}.todo-text{flex: 1}.delete-btn{background: #dc3545;color: white;border: none;border-radius: 50%;width: 2rem;height: 2rem;cursor: pointer;font-size: 1.2rem;display: flex;align-items: center;justify-content: center}.delete-btn:hover{background: #c82333}.empty-state{text-align: center;color: #666;font-style: italic;padding: 2rem}")
		_gsxgw.S("</style>")
		_gsxgw.S("</head>")
//line pages.gsx:217:3
		_gsxgw.S("<body")
		_gsxgw.S(">")
//line pages.gsx:218:4
		_gsxgw.S("<main")
		_gsxgw.S(" id=\"content\"")
		_gsxgw.S(">")
//line pages.gsx:219:5
		_gsxgw.Node(ctx, children)
		_gsxgw.S("</main>")
		_gsxgw.S("</body>")
		_gsxgw.S("</html>")
		return _gsxgw.Err()
	})
}

type ErrorPageProps struct {
	Err error
}

func ErrorPage(_gsxp ErrorPageProps) gsx.Node {
	return gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
		err := _gsxp.Err
		_gsxgw := gsx.W(_gsxw)
//line pages.gsx:226:2
		_gsxgw.Node(ctx, Layout(LayoutProps{Children: gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
			_gsxgw := gsx.W(_gsxw)
//line pages.gsx:227:3
			_gsxgw.Node(ctx, ErrorComp(ErrorCompProps{Err: err}))
			return _gsxgw.Err()
		})}))
		return _gsxgw.Err()
	})
}

type ErrorCompProps struct {
	Err error
}

func ErrorComp(_gsxp ErrorCompProps) gsx.Node {
	return gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
		err := _gsxp.Err
		_gsxgw := gsx.W(_gsxw)
//line pages.gsx:232:2
		_gsxgw.S("<h1")
		_gsxgw.S(">")
		_gsxgw.S("Error")
		_gsxgw.S("</h1>")
//line pages.gsx:233:2
		_gsxgw.S("<p")
		_gsxgw.S(">")
//line pages.gsx:233:5
		_gsxgw.Text(string(err.Error()))
		_gsxgw.S("</p>")
		return _gsxgw.Err()
	})
}
