// Code generated by gsx; DO NOT EDIT.

package main

import (
	"net/http"
	"strconv"

	_gsxctx "context"
	"github.com/gsxhq/gsx"
	_gsxrt "github.com/gsxhq/gsx"
	"github.com/jackielii/structpages"
	_gsxf0 "github.com/jackielii/structpages"
	_gsxio "io"
)

//line pages.gsx:11:1
type index struct {
	add        `route:"POST /add AddTodo"`
	toggle     `route:"POST /toggle/{id} ToggleTodo"`
	deleteTodo `route:"DELETE /delete/{id} DeleteTodo"`
}

//line pages.gsx:17:1
func (p index) Page() _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line pages.gsx:18:2
		_gsxgw.NodeResult(_gsxrenderLayout(ctx, _gsxgw, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
			_gsxgw := _gsxrt.W(_gsxw)
//line pages.gsx:19:3
			_gsxgw.S("<div class=\"todo-app\">")
//line pages.gsx:20:4
			_gsxgw.S("<h1>TODO App</h1>")
//line pages.gsx:21:4
			_gsxgw.S("<form")
			_gsxv0, _gsxerr := _gsxf0.URLFor(ctx, (add{}))
			if _gsxerr != nil {
				return _gsxerr
			}
			_gsxgw.S(" hx-post=\"")
			_gsxgw.AttrValue(string(_gsxv0))
			_gsxgw.S("\"")
			_gsxv1, _gsxerr := _gsxf0.IDTarget(ctx, (index.TodoList))
			if _gsxerr != nil {
				return _gsxerr
			}
			_gsxgw.S(" hx-target=\"")
			_gsxgw.AttrValue(string(_gsxv1))
			_gsxgw.S("\" hx-swap=\"innerHTML\" hx-on:htmx:after-request=\"this.reset()\">")
//line pages.gsx:27:5
			_gsxgw.S("<div class=\"form-group\">")
//line pages.gsx:28:6
			_gsxgw.S("<input type=\"text\" name=\"text\" placeholder=\"Add a new todo...\"")
			_gsxgw.BoolAttr("required", true)
			_gsxgw.S(">")
//line pages.gsx:34:6
			_gsxgw.S("<button type=\"submit\">Add Todo</button></div></form>")
//line pages.gsx:37:4
			_gsxgw.S("<div")
			_gsxv2, _gsxerr := _gsxf0.ID(ctx, (index.TodoList))
			if _gsxerr != nil {
				return _gsxerr
			}
			_gsxgw.S(" id=\"")
			_gsxgw.AttrValue(string(_gsxv2))
			_gsxgw.S("\">")
//line pages.gsx:38:5
			_gsxgw.Node(ctx, p.TodoList())
			_gsxgw.S("</div></div>")
			return _gsxgw.Err()
		})))
		return _gsxgw.Err()
	})
}

//line pages.gsx:44:1
func (p index) TodoList() _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line pages.gsx:45:2
		_gsxgw.NodeResult(_gsxrenderTodoList(ctx, _gsxgw))
		return _gsxgw.Err()
	})
}

/*line pages.gsx:46:2*/

type add struct{}

func (a add) ServeHTTP(w http.ResponseWriter, r *http.Request) error {
	if r.Method == "POST" {
		text := r.FormValue("text")
		if text != "" {
			addTodo(text)
		}
	}
	return structpages.RenderComponent(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line pages.gsx:57:37
		_gsxgw.NodeResult(_gsxrenderTodoList(ctx, _gsxgw))
		return _gsxgw.Err()
	}) /*line pages.gsx:57:48*/)
}

type toggle struct{}

func (t toggle) ServeHTTP(w http.ResponseWriter, r *http.Request) error {
	id, err := strconv.Atoi(r.PathValue("id"))
	if err != nil {
		return err
	}
	if r.Method == "POST" {
		toggleTodo(id)
	}
	return structpages.RenderComponent(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line pages.gsx:70:37
		_gsxgw.NodeResult(_gsxrenderTodoList(ctx, _gsxgw))
		return _gsxgw.Err()
	}) /*line pages.gsx:70:48*/)
}

type deleteTodo struct{}

func (d deleteTodo) ServeHTTP(w http.ResponseWriter, r *http.Request) error {
	id, err := strconv.Atoi(r.PathValue("id"))
	if err != nil {
		return err
	}
	if r.Method == "DELETE" {
		removeTodo(id)
	}
	return structpages.RenderComponent(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line pages.gsx:83:37
		_gsxgw.NodeResult(_gsxrenderTodoList(ctx, _gsxgw))
		return _gsxgw.Err()
	}) /*line pages.gsx:83:48*/)
}

//line pages.gsx:86:1
func TodoList() _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
		return _gsxrenderTodoList(ctx, _gsxgw)
	})
}

func _gsxrenderTodoList(ctx _gsxctx.Context, _gsxgw *_gsxrt.Writer) error {
	if _gsxerr := _gsxgw.Err(); _gsxerr != nil {
		return _gsxerr
	}
//line pages.gsx:87:2
	_gsxgw.S("<ul class=\"todo-list\">")
//line pages.gsx:88:3
	for _, todo := range getTodos() {
//line pages.gsx:89:4
		_gsxgw.S("<li class=\"")
		_gsxgw.Class(_gsxrt.DefaultClassMerge, _gsxrt.Class("todo-item"), _gsxrt.ClassIf("completed", todo.Completed))
		_gsxgw.S("\">")
//line pages.gsx:90:5
		_gsxgw.S("<div class=\"todo-content\">")
//line pages.gsx:91:6
		_gsxgw.S("<input type=\"checkbox\"")
		_gsxgw.BoolAttr("checked", bool(todo.Completed))
		_gsxv3, _gsxerr := _gsxf0.URLFor(ctx, (toggle{}), "id", todo.ID)
		if _gsxerr != nil {
			return _gsxerr
		}
		_gsxgw.S(" hx-post=\"")
		_gsxgw.AttrValue(string(_gsxv3))
		_gsxgw.S("\"")
		_gsxv4, _gsxerr := _gsxf0.IDTarget(ctx, (index.TodoList))
		if _gsxerr != nil {
			return _gsxerr
		}
		_gsxgw.S(" hx-target=\"")
		_gsxgw.AttrValue(string(_gsxv4))
		_gsxgw.S("\" hx-swap=\"innerHTML\">")
//line pages.gsx:98:6
		_gsxgw.S("<span class=\"todo-text\">")
//line pages.gsx:98:30
		_gsxgw.Text(string(todo.Text))
		_gsxgw.S("</span></div>")
//line pages.gsx:100:5
		_gsxgw.S("<button class=\"delete-btn\"")
		_gsxv5, _gsxerr := _gsxf0.URLFor(ctx, (deleteTodo{}), "id", todo.ID)
		if _gsxerr != nil {
			return _gsxerr
		}
		_gsxgw.S(" hx-delete=\"")
		_gsxgw.AttrValue(string(_gsxv5))
		_gsxgw.S("\"")
		_gsxv6, _gsxerr := _gsxf0.IDTarget(ctx, (index.TodoList))
		if _gsxerr != nil {
			return _gsxerr
		}
		_gsxgw.S(" hx-target=\"")
		_gsxgw.AttrValue(string(_gsxv6))
		_gsxgw.S("\" hx-swap=\"innerHTML\" hx-confirm=\"Are you sure you want to delete this todo?\">×</button></li>")
	}
	_gsxgw.S("</ul>")
//line pages.gsx:112:2
	if len(getTodos()) == 0 {
//line pages.gsx:113:3
		_gsxgw.S("<p class=\"empty-state\">No todos yet. Add one above!</p>")
	}
	return _gsxgw.Err()
}

//line pages.gsx:117:1
func Layout(children gsx.Node) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
		return _gsxrenderLayout(ctx, _gsxgw, children)
	})
}

func _gsxrenderLayout(ctx _gsxctx.Context, _gsxgw *_gsxrt.Writer, children gsx.Node) error {
	if _gsxerr := _gsxgw.Err(); _gsxerr != nil {
		return _gsxerr
	}
	_gsxgw.S("<!DOCTYPE html>")
//line pages.gsx:119:2
	_gsxgw.S("<html lang=\"en\">")
//line pages.gsx:120:3
	_gsxgw.S("<head>")
//line pages.gsx:121:4
	_gsxgw.S("<link rel=\"stylesheet\" href=\"https://unpkg.com/missing.css@1.1.3\">")
//line pages.gsx:122:4
	_gsxgw.S("<script src=\"https://unpkg.com/htmx.org@2.0.4\"")
	_gsxgw.Nonce(ctx)
	_gsxgw.S("></script>")
//line pages.gsx:123:4
	_gsxgw.S("<title>TODO App</title>")
//line pages.gsx:124:4
	_gsxgw.S("<style")
	_gsxgw.Nonce(ctx)
	_gsxgw.S(">\n.todo-app {\n\tmax-width: 600px;\n\tmargin: 2rem auto;\n\tpadding: 2rem;\n}\n\n.form-group {\n\tdisplay: flex;\n\tgap: 0.5rem;\n\tmargin-bottom: 2rem;\n}\n\n.form-group input {\n\tflex: 1;\n\tpadding: 0.75rem;\n\tborder: 1px solid #ddd;\n\tborder-radius: 4px;\n}\n\n.form-group button {\n\tpadding: 0.75rem 1.5rem;\n\tbackground: #007bff;\n\tcolor: white;\n\tborder: none;\n\tborder-radius: 4px;\n\tcursor: pointer;\n}\n\n.form-group button:hover {\n\tbackground: #0056b3;\n}\n\n.todo-list {\n\tlist-style: none;\n\tpadding: 0;\n}\n\n.todo-item {\n\tdisplay: flex;\n\talign-items: center;\n\tjustify-content: space-between;\n\tpadding: 1rem;\n\tborder: 1px solid #eee;\n\tborder-radius: 4px;\n\tmargin-bottom: 0.5rem;\n\tbackground: white;\n}\n\n.todo-item.completed {\n\topacity: 0.6;\n}\n\n.todo-item.completed .todo-text {\n\ttext-decoration: line-through;\n}\n\n.todo-content {\n\tdisplay: flex;\n\talign-items: center;\n\tgap: 0.75rem;\n\tflex: 1;\n}\n\n.todo-text {\n\tflex: 1;\n}\n\n.delete-btn {\n\tbackground: #dc3545;\n\tcolor: white;\n\tborder: none;\n\tborder-radius: 50%;\n\twidth: 2rem;\n\theight: 2rem;\n\tcursor: pointer;\n\tfont-size: 1.2rem;\n\tdisplay: flex;\n\talign-items: center;\n\tjustify-content: center;\n}\n\n.delete-btn:hover {\n\tbackground: #c82333;\n}\n\n.empty-state {\n\ttext-align: center;\n\tcolor: #666;\n\tfont-style: italic;\n\tpadding: 2rem;\n}\n</style></head>")
//line pages.gsx:218:3
	_gsxgw.S("<body>")
//line pages.gsx:219:4
	_gsxgw.S("<main id=\"content\">")
//line pages.gsx:219:23
	_gsxgw.Node(ctx, children)
	_gsxgw.S("</main></body></html>")
	return _gsxgw.Err()
}

//line pages.gsx:224:1
func ErrorPage(err error) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line pages.gsx:225:2
		_gsxgw.NodeResult(_gsxrenderLayout(ctx, _gsxgw, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
			_gsxgw := _gsxrt.W(_gsxw)
//line pages.gsx:226:3
			_gsxgw.NodeResult(_gsxrenderErrorComp(ctx, _gsxgw, err))
			return _gsxgw.Err()
		})))
		return _gsxgw.Err()
	})
}

//line pages.gsx:230:1
func ErrorComp(err error) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
		return _gsxrenderErrorComp(ctx, _gsxgw, err)
	})
}

func _gsxrenderErrorComp(ctx _gsxctx.Context, _gsxgw *_gsxrt.Writer, err error) error {
	if _gsxerr := _gsxgw.Err(); _gsxerr != nil {
		return _gsxerr
	}
//line pages.gsx:231:2
	_gsxgw.S("<h1>Error</h1>")
//line pages.gsx:232:2
	_gsxgw.S("<p>")
//line pages.gsx:232:5
	_gsxgw.Text(string(err.Error()))
	_gsxgw.S("</p>")
	return _gsxgw.Err()
}
