// Code generated by gsx; DO NOT EDIT.

package main

import (
	_gsxctx "context"
	"github.com/gsxhq/gsx"
	_gsxrt "github.com/gsxhq/gsx"
	_gsxf0 "github.com/jackielii/structpages"
	_gsxio "io"
)

// Page structs + route tags are plain Go — pass through unchanged.
//
//line pages.gsx:5:1
type index struct {
	product `route:"/product Product"`
	team    `route:"/team Team"`
	contact `route:"/contact Contact"`
}
type product struct{}
type team struct{}
type contact struct{}

//line pages.gsx:15:1
func (p index) Page() _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line pages.gsx:16:2
		_gsxgw.NodeResult(_gsxrenderLayout(ctx, _gsxgw, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
			_gsxgw := _gsxrt.W(_gsxw)
//line pages.gsx:17:3
			_gsxgw.S("<h1>Welcome to the Index Page</h1>")
//line pages.gsx:18:3
			_gsxgw.S("<p>Navigate to the product, team, or contact pages using the links below:</p>")
			return _gsxgw.Err()
		})))
		return _gsxgw.Err()
	})
}

//line pages.gsx:24:1
func (p product) Page() _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line pages.gsx:25:2
		_gsxgw.NodeResult(_gsxrenderLayout(ctx, _gsxgw, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
			_gsxgw := _gsxrt.W(_gsxw)
//line pages.gsx:26:3
			_gsxgw.S("<h1>Product Page</h1>")
//line pages.gsx:27:3
			_gsxgw.S("<p>This is the product page.</p>")
			return _gsxgw.Err()
		})))
		return _gsxgw.Err()
	})
}

//line pages.gsx:31:1
func (p team) Page() _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line pages.gsx:32:2
		_gsxgw.NodeResult(_gsxrenderLayout(ctx, _gsxgw, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
			_gsxgw := _gsxrt.W(_gsxw)
//line pages.gsx:33:3
			_gsxgw.S("<h1>Team Page</h1>")
//line pages.gsx:34:3
			_gsxgw.S("<p>This is the team page.</p>")
			return _gsxgw.Err()
		})))
		return _gsxgw.Err()
	})
}

//line pages.gsx:38:1
func (p contact) Page() _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line pages.gsx:39:2
		_gsxgw.NodeResult(_gsxrenderLayout(ctx, _gsxgw, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
			_gsxgw := _gsxrt.W(_gsxw)
//line pages.gsx:40:3
			_gsxgw.S("<h1>Contact Page</h1>")
//line pages.gsx:41:3
			_gsxgw.S("<p>This is the contact page.</p>")
			return _gsxgw.Err()
		})))
		return _gsxgw.Err()
	})
}

//line pages.gsx:45:1
func Layout(children gsx.Node) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
		return _gsxrenderLayout(ctx, _gsxgw, children)
	})
}

func _gsxrenderLayout(ctx _gsxctx.Context, _gsxgw *_gsxrt.Writer, children gsx.Node) error {
	if _gsxerr := _gsxgw.Err(); _gsxerr != nil {
		return _gsxerr
	}
	_gsxgw.S("<!DOCTYPE html>")
//line pages.gsx:47:2
	_gsxgw.S("<html lang=\"en\">")
//line pages.gsx:48:3
	_gsxgw.S("<head>")
//line pages.gsx:49:4
	_gsxgw.S("<link rel=\"stylesheet\" href=\"https://unpkg.com/missing.css@1.1.3\">")
//line pages.gsx:50:4
	_gsxgw.S("<title>Simple Example</title></head>")
//line pages.gsx:52:3
	_gsxgw.S("<body>")
//line pages.gsx:53:4
	_gsxgw.S("<header class=\"navbar\">")
//line pages.gsx:54:5
	_gsxgw.S("<nav>")
//line pages.gsx:55:6
	_gsxgw.S("<ul role=\"list\">")
//line pages.gsx:56:7
	_gsxgw.S("<li>")
//line pages.gsx:57:8
	_gsxgw.S("<a")
	_gsxv0, _gsxerr := _gsxf0.URLFor(ctx, (index{}))
	if _gsxerr != nil {
		return _gsxerr
	}
	_gsxgw.S(" href=\"")
	_gsxgw.URL(string(_gsxv0))
	_gsxgw.S("\">Home</a></li>")
//line pages.gsx:59:7
	_gsxgw.S("<li>")
//line pages.gsx:60:8
	_gsxgw.S("<a")
	_gsxv1, _gsxerr := _gsxf0.URLFor(ctx, (product{}))
	if _gsxerr != nil {
		return _gsxerr
	}
	_gsxgw.S(" href=\"")
	_gsxgw.URL(string(_gsxv1))
	_gsxgw.S("\">Product</a></li>")
//line pages.gsx:62:7
	_gsxgw.S("<li>")
//line pages.gsx:63:8
	_gsxgw.S("<a")
	_gsxv2, _gsxerr := _gsxf0.URLFor(ctx, (team{}))
	if _gsxerr != nil {
		return _gsxerr
	}
	_gsxgw.S(" href=\"")
	_gsxgw.URL(string(_gsxv2))
	_gsxgw.S("\">Team</a></li>")
//line pages.gsx:65:7
	_gsxgw.S("<li>")
//line pages.gsx:66:8
	_gsxgw.S("<a")
	_gsxv3, _gsxerr := _gsxf0.URLFor(ctx, (contact{}))
	if _gsxerr != nil {
		return _gsxerr
	}
	_gsxgw.S(" href=\"")
	_gsxgw.URL(string(_gsxv3))
	_gsxgw.S("\">Contact</a></li></ul></nav></header>")
//line pages.gsx:71:4
	_gsxgw.S("<main>")
//line pages.gsx:71:10
	_gsxgw.Node(ctx, children)
	_gsxgw.S("</main></body></html>")
	return _gsxgw.Err()
}
