// Code generated by gsx; DO NOT EDIT.

package main

import (
	"context"
	"io"

	"github.com/gsxhq/gsx"
	_gsxf0 "github.com/jackielii/structpages"
)

// Page structs + route tags are plain Go — pass through unchanged.
type index struct {
	product `route:"/product Product"`
	team    `route:"/team Team"`
	contact `route:"/contact Contact"`
}
type product struct{}
type team struct{}
type contact struct{}

func (p index) Page() gsx.Node {
	return gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
		_gsxgw := gsx.W(_gsxw)
//line pages.gsx:14:2
		_gsxgw.Node(ctx, Layout(LayoutProps{Children: gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
			_gsxgw := gsx.W(_gsxw)
//line pages.gsx:15:3
			_gsxgw.S("<h1>Welcome to the Index Page</h1>")
//line pages.gsx:16:3
			_gsxgw.S("<p>Navigate to the product, team, or contact pages using the links below:</p>")
			return _gsxgw.Err()
		})}))
		return _gsxgw.Err()
	})
}

func (p product) Page() gsx.Node {
	return gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
		_gsxgw := gsx.W(_gsxw)
//line pages.gsx:23:2
		_gsxgw.Node(ctx, Layout(LayoutProps{Children: gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
			_gsxgw := gsx.W(_gsxw)
//line pages.gsx:24:3
			_gsxgw.S("<h1>Product Page</h1>")
//line pages.gsx:25:3
			_gsxgw.S("<p>This is the product page.</p>")
			return _gsxgw.Err()
		})}))
		return _gsxgw.Err()
	})
}

func (p team) Page() gsx.Node {
	return gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
		_gsxgw := gsx.W(_gsxw)
//line pages.gsx:30:2
		_gsxgw.Node(ctx, Layout(LayoutProps{Children: gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
			_gsxgw := gsx.W(_gsxw)
//line pages.gsx:31:3
			_gsxgw.S("<h1>Team Page</h1>")
//line pages.gsx:32:3
			_gsxgw.S("<p>This is the team page.</p>")
			return _gsxgw.Err()
		})}))
		return _gsxgw.Err()
	})
}

func (p contact) Page() gsx.Node {
	return gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
		_gsxgw := gsx.W(_gsxw)
//line pages.gsx:37:2
		_gsxgw.Node(ctx, Layout(LayoutProps{Children: gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
			_gsxgw := gsx.W(_gsxw)
//line pages.gsx:38:3
			_gsxgw.S("<h1>Contact Page</h1>")
//line pages.gsx:39:3
			_gsxgw.S("<p>This is the contact page.</p>")
			return _gsxgw.Err()
		})}))
		return _gsxgw.Err()
	})
}

type LayoutProps struct {
	Children gsx.Node
}

func Layout(_gsxp LayoutProps) gsx.Node {
	return gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
		children := _gsxp.Children
		_gsxgw := gsx.W(_gsxw)
		_gsxgw.S("<!DOCTYPE html>")
//line pages.gsx:45:2
		_gsxgw.S("<html lang=\"en\">")
//line pages.gsx:46:3
		_gsxgw.S("<head>")
//line pages.gsx:47:4
		_gsxgw.S("<link rel=\"stylesheet\" href=\"https://unpkg.com/missing.css@1.1.3\"/>")
//line pages.gsx:48:4
		_gsxgw.S("<title>Simple Example</title></head>")
//line pages.gsx:50:3
		_gsxgw.S("<body>")
//line pages.gsx:51:4
		_gsxgw.S("<header class=\"navbar\">")
//line pages.gsx:52:5
		_gsxgw.S("<nav>")
//line pages.gsx:53:6
		_gsxgw.S("<ul role=\"list\">")
//line pages.gsx:54:7
		_gsxgw.S("<li>")
//line pages.gsx:55:8
		_gsxgw.S("<a")
		_gsxv0, _gsxerr := _gsxf0.URLFor(ctx, (index{}))
		if _gsxerr != nil {
			return _gsxerr
		}
		_gsxgw.S(" href=\"")
		_gsxgw.URL(string(_gsxv0))
		_gsxgw.S("\">Home</a></li>")
//line pages.gsx:57:7
		_gsxgw.S("<li>")
//line pages.gsx:58:8
		_gsxgw.S("<a")
		_gsxv1, _gsxerr := _gsxf0.URLFor(ctx, (product{}))
		if _gsxerr != nil {
			return _gsxerr
		}
		_gsxgw.S(" href=\"")
		_gsxgw.URL(string(_gsxv1))
		_gsxgw.S("\">Product</a></li>")
//line pages.gsx:60:7
		_gsxgw.S("<li>")
//line pages.gsx:61:8
		_gsxgw.S("<a")
		_gsxv2, _gsxerr := _gsxf0.URLFor(ctx, (team{}))
		if _gsxerr != nil {
			return _gsxerr
		}
		_gsxgw.S(" href=\"")
		_gsxgw.URL(string(_gsxv2))
		_gsxgw.S("\">Team</a></li>")
//line pages.gsx:63:7
		_gsxgw.S("<li>")
//line pages.gsx:64:8
		_gsxgw.S("<a")
		_gsxv3, _gsxerr := _gsxf0.URLFor(ctx, (contact{}))
		if _gsxerr != nil {
			return _gsxerr
		}
		_gsxgw.S(" href=\"")
		_gsxgw.URL(string(_gsxv3))
		_gsxgw.S("\">Contact</a></li></ul></nav></header>")
//line pages.gsx:69:4
		_gsxgw.S("<main>")
//line pages.gsx:69:10
		_gsxgw.Node(ctx, children)
		_gsxgw.S("</main></body></html>")
		return _gsxgw.Err()
	})
}
