// Code generated by gsx; DO NOT EDIT.

package main

import (
	"context"
	"io"

	"github.com/gsxhq/gsx"
	"github.com/jackielii/structpages"
)

// Page structs + route tags are plain Go — pass through unchanged.
type index struct {
	product `route:"/product Product"`
	team    `route:"/team Team"`
	contact `route:"/contact Contact"`
}
type product struct{}
type team struct{}
type contact struct{}

func (p index) Page() gsx.Node {
	return gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
		_gsxgw := gsx.W(_gsxw)
//line pages.gsx:16:2
		_gsxgw.Node(ctx, Layout(LayoutProps{Children: gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
			_gsxgw := gsx.W(_gsxw)
//line pages.gsx:17:3
			_gsxgw.S("<h1")
			_gsxgw.S(">")
			_gsxgw.S("Welcome to the Index Page")
			_gsxgw.S("</h1>")
//line pages.gsx:18:3
			_gsxgw.S("<p")
			_gsxgw.S(">")
			_gsxgw.S("Navigate to the product, team, or contact pages using the links below:")
			_gsxgw.S("</p>")
			return _gsxgw.Err()
		})}))
		return _gsxgw.Err()
	})
}

func (p product) Page() gsx.Node {
	return gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
		_gsxgw := gsx.W(_gsxw)
//line pages.gsx:23:2
		_gsxgw.Node(ctx, Layout(LayoutProps{Children: gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
			_gsxgw := gsx.W(_gsxw)
//line pages.gsx:24:3
			_gsxgw.S("<h1")
			_gsxgw.S(">")
			_gsxgw.S("Product Page")
			_gsxgw.S("</h1>")
//line pages.gsx:25:3
			_gsxgw.S("<p")
			_gsxgw.S(">")
			_gsxgw.S("This is the product page.")
			_gsxgw.S("</p>")
			return _gsxgw.Err()
		})}))
		return _gsxgw.Err()
	})
}

func (p team) Page() gsx.Node {
	return gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
		_gsxgw := gsx.W(_gsxw)
//line pages.gsx:30:2
		_gsxgw.Node(ctx, Layout(LayoutProps{Children: gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
			_gsxgw := gsx.W(_gsxw)
//line pages.gsx:31:3
			_gsxgw.S("<h1")
			_gsxgw.S(">")
			_gsxgw.S("Team Page")
			_gsxgw.S("</h1>")
//line pages.gsx:32:3
			_gsxgw.S("<p")
			_gsxgw.S(">")
			_gsxgw.S("This is the team page.")
			_gsxgw.S("</p>")
			return _gsxgw.Err()
		})}))
		return _gsxgw.Err()
	})
}

func (p contact) Page() gsx.Node {
	return gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
		_gsxgw := gsx.W(_gsxw)
//line pages.gsx:37:2
		_gsxgw.Node(ctx, Layout(LayoutProps{Children: gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
			_gsxgw := gsx.W(_gsxw)
//line pages.gsx:38:3
			_gsxgw.S("<h1")
			_gsxgw.S(">")
			_gsxgw.S("Contact Page")
			_gsxgw.S("</h1>")
//line pages.gsx:39:3
			_gsxgw.S("<p")
			_gsxgw.S(">")
			_gsxgw.S("This is the contact page.")
			_gsxgw.S("</p>")
			return _gsxgw.Err()
		})}))
		return _gsxgw.Err()
	})
}

type LayoutProps struct {
	Children gsx.Node
}

func Layout(_gsxp LayoutProps) gsx.Node {
	return gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
		children := _gsxp.Children
		_gsxgw := gsx.W(_gsxw)
		_gsxgw.S("<!DOCTYPE html>")
//line pages.gsx:45:2
		_gsxgw.S("<html")
		_gsxgw.S(" lang=\"en\"")
		_gsxgw.S(">")
//line pages.gsx:46:3
		_gsxgw.S("<head")
		_gsxgw.S(">")
//line pages.gsx:47:4
		_gsxgw.S("<link")
		_gsxgw.S(" rel=\"stylesheet\"")
		_gsxgw.S(" href=\"https://unpkg.com/missing.css@1.1.3\"")
		_gsxgw.S("/>")
//line pages.gsx:48:4
		_gsxgw.S("<title")
		_gsxgw.S(">")
		_gsxgw.S("Simple Example")
		_gsxgw.S("</title>")
		_gsxgw.S("</head>")
//line pages.gsx:50:3
		_gsxgw.S("<body")
		_gsxgw.S(">")
//line pages.gsx:51:4
		_gsxgw.S("<header")
		_gsxgw.S(" class=\"navbar\"")
		_gsxgw.S(">")
//line pages.gsx:52:5
		_gsxgw.S("<nav")
		_gsxgw.S(">")
//line pages.gsx:53:6
		_gsxgw.S("<ul")
		_gsxgw.S(" role=\"list\"")
		_gsxgw.S(">")
//line pages.gsx:54:7
		_gsxgw.S("<li")
		_gsxgw.S(">")
//line pages.gsx:54:11
		_gsxgw.S("<a")
		_gsxv0, _gsxerr := urlFor(ctx, index{})
		if _gsxerr != nil {
			return _gsxerr
		}
		_gsxgw.S(" href=\"")
		_gsxgw.URL(string(_gsxv0))
		_gsxgw.S("\"")
		_gsxgw.S(">")
		_gsxgw.S("Home")
		_gsxgw.S("</a>")
		_gsxgw.S("</li>")
//line pages.gsx:55:7
		_gsxgw.S("<li")
		_gsxgw.S(">")
//line pages.gsx:55:11
		_gsxgw.S("<a")
		_gsxv1, _gsxerr := urlFor(ctx, product{})
		if _gsxerr != nil {
			return _gsxerr
		}
		_gsxgw.S(" href=\"")
		_gsxgw.URL(string(_gsxv1))
		_gsxgw.S("\"")
		_gsxgw.S(">")
		_gsxgw.S("Product")
		_gsxgw.S("</a>")
		_gsxgw.S("</li>")
//line pages.gsx:56:7
		_gsxgw.S("<li")
		_gsxgw.S(">")
//line pages.gsx:56:11
		_gsxgw.S("<a")
		_gsxv2, _gsxerr := urlFor(ctx, team{})
		if _gsxerr != nil {
			return _gsxerr
		}
		_gsxgw.S(" href=\"")
		_gsxgw.URL(string(_gsxv2))
		_gsxgw.S("\"")
		_gsxgw.S(">")
		_gsxgw.S("Team")
		_gsxgw.S("</a>")
		_gsxgw.S("</li>")
//line pages.gsx:57:7
		_gsxgw.S("<li")
		_gsxgw.S(">")
//line pages.gsx:57:11
		_gsxgw.S("<a")
		_gsxv3, _gsxerr := urlFor(ctx, contact{})
		if _gsxerr != nil {
			return _gsxerr
		}
		_gsxgw.S(" href=\"")
		_gsxgw.URL(string(_gsxv3))
		_gsxgw.S("\"")
		_gsxgw.S(">")
		_gsxgw.S("Contact")
		_gsxgw.S("</a>")
		_gsxgw.S("</li>")
		_gsxgw.S("</ul>")
		_gsxgw.S("</nav>")
		_gsxgw.S("</header>")
//line pages.gsx:61:4
		_gsxgw.S("<main")
		_gsxgw.S(">")
//line pages.gsx:61:10
		_gsxgw.Node(ctx, children)
		_gsxgw.S("</main>")
		_gsxgw.S("</body>")
		_gsxgw.S("</html>")
		return _gsxgw.Err()
	})
}

var urlFor = structpages.URLFor
