// Code generated by gsx; DO NOT EDIT.

package layout

import (
	"context"
	"io"

	"github.com/gsxhq/gsx"
	"github.com/jackielii/structpages"
	"github.com/jackielii/structpages/examples/blog/store"
)

// PublicShell wraps reader-facing pages. Cross-feature links (e.g. the admin
// link) use structpages.Ref so this package never imports admin or blog —
// keeping the dependency graph one-way (features → ui).

type PublicShellProps struct {
	Title    string
	Children gsx.Node
}

func PublicShell(_gsxp PublicShellProps) gsx.Node {
	return gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
		title := _gsxp.Title
		children := _gsxp.Children
		_gsxgw := gsx.W(_gsxw)
		_gsxgw.S("<!DOCTYPE html>")
//line layout.gsx:16:2
		_gsxgw.S("<html")
		_gsxgw.S(" lang=\"en\"")
		_gsxgw.S(">")
//line layout.gsx:17:3
		_gsxgw.S("<head")
		_gsxgw.S(">")
//line layout.gsx:18:4
		_gsxgw.S("<meta")
		_gsxgw.S(" charset=\"utf-8\"")
		_gsxgw.S("/>")
//line layout.gsx:19:4
		_gsxgw.S("<meta")
		_gsxgw.S(" name=\"viewport\"")
		_gsxgw.S(" content=\"width=device-width, initial-scale=1\"")
		_gsxgw.S("/>")
//line layout.gsx:20:4
		_gsxgw.S("<title")
		_gsxgw.S(">")
//line layout.gsx:20:11
		_gsxgw.Text(string(title))
		_gsxgw.S(" — structpages blog")
		_gsxgw.S("</title>")
//line layout.gsx:21:4
		_gsxgw.S("<script")
		_gsxgw.S(" src=\"https://cdn.tailwindcss.com\"")
		_gsxgw.S(">")
		_gsxgw.S("</script>")
//line layout.gsx:22:4
		_gsxgw.S("<script")
		_gsxgw.S(" src=\"https://unpkg.com/htmx.org@2.0.4\"")
		_gsxgw.S(">")
		_gsxgw.S("</script>")
		_gsxgw.S("</head>")
//line layout.gsx:24:3
		_gsxgw.S("<body")
		_gsxgw.S(" class=\"bg-slate-50 text-slate-900\"")
		_gsxgw.S(">")
//line layout.gsx:25:4
		_gsxgw.S("<header")
		_gsxgw.S(" class=\"border-b bg-white\"")
		_gsxgw.S(">")
//line layout.gsx:26:5
		_gsxgw.S("<div")
		_gsxgw.S(" class=\"mx-auto flex max-w-3xl items-center justify-between px-4 py-3\"")
		_gsxgw.S(">")
//line layout.gsx:27:6
		_gsxgw.S("<a")
		_gsxgw.S(" class=\"text-lg font-semibold\"")
		_gsxv0, _gsxerr := structpages.URLFor(ctx, structpages.Ref("home"))
		if _gsxerr != nil {
			return _gsxerr
		}
		_gsxgw.S(" href=\"")
		_gsxgw.URL(string(_gsxv0))
		_gsxgw.S("\"")
		_gsxgw.S(">")
		_gsxgw.S("structpages blog")
		_gsxgw.S("</a>")
//line layout.gsx:28:6
		_gsxgw.S("<nav")
		_gsxgw.S(" class=\"flex gap-4 text-sm\"")
		_gsxgw.S(">")
//line layout.gsx:29:7
		_gsxgw.S("<a")
		_gsxgw.S(" class=\"hover:underline\"")
		_gsxv1, _gsxerr := structpages.URLFor(ctx, structpages.Ref("home"))
		if _gsxerr != nil {
			return _gsxerr
		}
		_gsxgw.S(" href=\"")
		_gsxgw.URL(string(_gsxv1))
		_gsxgw.S("\"")
		_gsxgw.S(">")
		_gsxgw.S("Home")
		_gsxgw.S("</a>")
//line layout.gsx:30:7
		_gsxgw.S("<a")
		_gsxgw.S(" class=\"hover:underline\"")
		_gsxv2, _gsxerr := structpages.URLFor(ctx, structpages.Ref("search"))
		if _gsxerr != nil {
			return _gsxerr
		}
		_gsxgw.S(" href=\"")
		_gsxgw.URL(string(_gsxv2))
		_gsxgw.S("\"")
		_gsxgw.S(">")
		_gsxgw.S("Search")
		_gsxgw.S("</a>")
//line layout.gsx:31:7
		_gsxgw.S("<a")
		_gsxgw.S(" class=\"text-slate-500 hover:text-slate-900\"")
		_gsxv3, _gsxerr := structpages.URLFor(ctx, structpages.Ref("loginPage"))
		if _gsxerr != nil {
			return _gsxerr
		}
		_gsxgw.S(" href=\"")
		_gsxgw.URL(string(_gsxv3))
		_gsxgw.S("\"")
		_gsxgw.S(">")
		_gsxgw.S("Admin")
		_gsxgw.S("</a>")
		_gsxgw.S("</nav>")
		_gsxgw.S("</div>")
		_gsxgw.S("</header>")
//line layout.gsx:35:4
		_gsxgw.S("<main")
		_gsxgw.S(" id=\"content\"")
		_gsxgw.S(" class=\"mx-auto max-w-3xl px-4 py-8\"")
		_gsxgw.S(">")
//line layout.gsx:36:5
		_gsxgw.Node(ctx, children)
		_gsxgw.S("</main>")
		_gsxgw.S("</body>")
		_gsxgw.S("</html>")
		return _gsxgw.Err()
	})
}

// AdminShell wraps the authenticated admin app.

type AdminShellProps struct {
	Title    string
	Current  store.User
	Children gsx.Node
}

func AdminShell(_gsxp AdminShellProps) gsx.Node {
	return gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
		title := _gsxp.Title
		current := _gsxp.Current
		children := _gsxp.Children
		_gsxgw := gsx.W(_gsxw)
		_gsxgw.S("<!DOCTYPE html>")
//line layout.gsx:45:2
		_gsxgw.S("<html")
		_gsxgw.S(" lang=\"en\"")
		_gsxgw.S(">")
//line layout.gsx:46:3
		_gsxgw.S("<head")
		_gsxgw.S(">")
//line layout.gsx:47:4
		_gsxgw.S("<meta")
		_gsxgw.S(" charset=\"utf-8\"")
		_gsxgw.S("/>")
//line layout.gsx:48:4
		_gsxgw.S("<meta")
		_gsxgw.S(" name=\"viewport\"")
		_gsxgw.S(" content=\"width=device-width, initial-scale=1\"")
		_gsxgw.S("/>")
//line layout.gsx:49:4
		_gsxgw.S("<title")
		_gsxgw.S(">")
		_gsxgw.S("Admin — ")
//line layout.gsx:49:21
		_gsxgw.Text(string(title))
		_gsxgw.S("</title>")
//line layout.gsx:50:4
		_gsxgw.S("<script")
		_gsxgw.S(" src=\"https://cdn.tailwindcss.com\"")
		_gsxgw.S(">")
		_gsxgw.S("</script>")
//line layout.gsx:51:4
		_gsxgw.S("<script")
		_gsxgw.S(" src=\"https://unpkg.com/htmx.org@2.0.4\"")
		_gsxgw.S(">")
		_gsxgw.S("</script>")
		_gsxgw.S("</head>")
//line layout.gsx:53:3
		_gsxgw.S("<body")
		_gsxgw.S(" class=\"bg-slate-100 text-slate-900\"")
		_gsxgw.S(">")
//line layout.gsx:54:4
		_gsxgw.S("<header")
		_gsxgw.S(" class=\"border-b bg-slate-900 text-slate-100\"")
		_gsxgw.S(">")
//line layout.gsx:55:5
		_gsxgw.S("<div")
		_gsxgw.S(" class=\"mx-auto flex max-w-5xl items-center justify-between px-4 py-3\"")
		_gsxgw.S(">")
//line layout.gsx:56:6
		_gsxgw.S("<a")
		_gsxgw.S(" class=\"flex items-center gap-2 text-lg font-semibold\"")
		_gsxv4, _gsxerr := structpages.URLFor(ctx, structpages.Ref("dashboard"))
		if _gsxerr != nil {
			return _gsxerr
		}
		_gsxgw.S(" href=\"")
		_gsxgw.URL(string(_gsxv4))
		_gsxgw.S("\"")
		_gsxgw.S(">")
//line layout.gsx:57:7
		_gsxgw.S("<img")
		_gsxgw.S(" src=\"/admin/static/admin-logo.svg\"")
		_gsxgw.S(" alt=\"\"")
		_gsxgw.S(" class=\"h-5 w-5\"")
		_gsxgw.S("/>")
		_gsxgw.S("blog admin")
		_gsxgw.S("</a>")
//line layout.gsx:60:6
		_gsxgw.S("<nav")
		_gsxgw.S(" class=\"flex items-center gap-4 text-sm\"")
		_gsxgw.S(">")
//line layout.gsx:61:7
		_gsxgw.S("<a")
		_gsxgw.S(" class=\"hover:underline\"")
		_gsxv5, _gsxerr := structpages.URLFor(ctx, structpages.Ref("dashboard"))
		if _gsxerr != nil {
			return _gsxerr
		}
		_gsxgw.S(" href=\"")
		_gsxgw.URL(string(_gsxv5))
		_gsxgw.S("\"")
		_gsxgw.S(">")
		_gsxgw.S("Dashboard")
		_gsxgw.S("</a>")
//line layout.gsx:62:7
		_gsxgw.S("<a")
		_gsxgw.S(" class=\"hover:underline\"")
		_gsxv6, _gsxerr := structpages.URLFor(ctx, structpages.Ref("postList"))
		if _gsxerr != nil {
			return _gsxerr
		}
		_gsxgw.S(" href=\"")
		_gsxgw.URL(string(_gsxv6))
		_gsxgw.S("\"")
		_gsxgw.S(">")
		_gsxgw.S("Posts")
		_gsxgw.S("</a>")
//line layout.gsx:63:7
		_gsxgw.S("<a")
		_gsxgw.S(" class=\"hover:underline\"")
		_gsxv7, _gsxerr := structpages.URLFor(ctx, structpages.Ref("userList"))
		if _gsxerr != nil {
			return _gsxerr
		}
		_gsxgw.S(" href=\"")
		_gsxgw.URL(string(_gsxv7))
		_gsxgw.S("\"")
		_gsxgw.S(">")
		_gsxgw.S("Users")
		_gsxgw.S("</a>")
//line layout.gsx:64:7
		_gsxgw.S("<span")
		_gsxgw.S(" class=\"text-slate-400\"")
		_gsxgw.S(">")
		_gsxgw.S("|")
		_gsxgw.S("</span>")
//line layout.gsx:65:7
		_gsxgw.S("<span")
		_gsxgw.S(" class=\"text-slate-300\"")
		_gsxgw.S(">")
//line layout.gsx:65:36
		_gsxgw.Text(string(current.Username))
		_gsxgw.S("</span>")
//line layout.gsx:66:7
		_gsxgw.S("<form")
		_gsxgw.S(" method=\"POST\"")
		_gsxv8, _gsxerr := structpages.URLFor(ctx, structpages.Ref("logout"))
		if _gsxerr != nil {
			return _gsxerr
		}
		_gsxgw.S(" action=\"")
		_gsxgw.URL(string(_gsxv8))
		_gsxgw.S("\"")
		_gsxgw.S(" class=\"m-0\"")
		_gsxgw.S(">")
//line layout.gsx:67:8
		_gsxgw.S("<button")
		_gsxgw.S(" class=\"text-slate-300 hover:text-white\"")
		_gsxgw.S(" type=\"submit\"")
		_gsxgw.S(">")
		_gsxgw.S("Sign out")
		_gsxgw.S("</button>")
		_gsxgw.S("</form>")
		_gsxgw.S("</nav>")
		_gsxgw.S("</div>")
		_gsxgw.S("</header>")
//line layout.gsx:72:4
		_gsxgw.S("<main")
		_gsxgw.S(" id=\"content\"")
		_gsxgw.S(" class=\"mx-auto max-w-5xl px-4 py-8\"")
		_gsxgw.S(">")
//line layout.gsx:73:5
		_gsxgw.Node(ctx, children)
		_gsxgw.S("</main>")
		_gsxgw.S("</body>")
		_gsxgw.S("</html>")
		return _gsxgw.Err()
	})
}
