// Code generated by gsx; DO NOT EDIT.

package layout

import (
	"context"
	"io"

	"github.com/gsxhq/gsx"
	"github.com/jackielii/structpages"
	_gsxf0 "github.com/jackielii/structpages"
	"github.com/jackielii/structpages/examples/blog/store"
)

// PublicShell wraps reader-facing pages. Cross-feature links (e.g. the admin
// link) use structpages.Ref so this package never imports admin or blog —
// keeping the dependency graph one-way (features → ui).

type PublicShellProps struct {
	Title    string
	Children gsx.Node
}

//line layout.gsx:14:1
func PublicShell(_gsxp PublicShellProps) gsx.Node {
	return gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
		title := _gsxp.Title
		children := _gsxp.Children
		_gsxgw := gsx.W(_gsxw)
		_gsxgw.S("<!DOCTYPE html>")
//line layout.gsx:16:2
		_gsxgw.S("<html lang=\"en\">")
//line layout.gsx:17:3
		_gsxgw.S("<head>")
//line layout.gsx:18:4
		_gsxgw.S("<meta charset=\"utf-8\"/>")
//line layout.gsx:19:4
		_gsxgw.S("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"/>")
//line layout.gsx:23:4
		_gsxgw.S("<title>")
//line layout.gsx:23:11
		_gsxgw.Text(string(title))
		_gsxgw.S(" — structpages blog</title>")
//line layout.gsx:24:4
		_gsxgw.S("<script src=\"https://cdn.tailwindcss.com\"></script>")
//line layout.gsx:25:4
		_gsxgw.S("<script src=\"https://unpkg.com/htmx.org@2.0.4\"></script></head>")
//line layout.gsx:27:3
		_gsxgw.S("<body class=\"bg-slate-50 text-slate-900\">")
//line layout.gsx:28:4
		_gsxgw.S("<header class=\"border-b bg-white\">")
//line layout.gsx:29:5
		_gsxgw.S("<div class=\"mx-auto flex max-w-3xl items-center justify-between px-4 py-3\">")
//line layout.gsx:32:6
		_gsxgw.S("<a class=\"text-lg font-semibold\"")
		_gsxv0, _gsxerr := _gsxf0.URLFor(ctx, (structpages.Ref("home")))
		if _gsxerr != nil {
			return _gsxerr
		}
		_gsxgw.S(" href=\"")
		_gsxgw.URL(string(_gsxv0))
		_gsxgw.S("\">structpages blog</a>")
//line layout.gsx:38:6
		_gsxgw.S("<nav class=\"flex gap-4 text-sm\">")
//line layout.gsx:39:7
		_gsxgw.S("<a class=\"hover:underline\"")
		_gsxv1, _gsxerr := _gsxf0.URLFor(ctx, (structpages.Ref("home")))
		if _gsxerr != nil {
			return _gsxerr
		}
		_gsxgw.S(" href=\"")
		_gsxgw.URL(string(_gsxv1))
		_gsxgw.S("\">Home</a>")
//line layout.gsx:45:7
		_gsxgw.S("<a class=\"hover:underline\"")
		_gsxv2, _gsxerr := _gsxf0.URLFor(ctx, (structpages.Ref("search")))
		if _gsxerr != nil {
			return _gsxerr
		}
		_gsxgw.S(" href=\"")
		_gsxgw.URL(string(_gsxv2))
		_gsxgw.S("\">Search</a>")
//line layout.gsx:51:7
		_gsxgw.S("<a class=\"text-slate-500 hover:text-slate-900\"")
		_gsxv3, _gsxerr := _gsxf0.URLFor(ctx, (structpages.Ref("loginPage")))
		if _gsxerr != nil {
			return _gsxerr
		}
		_gsxgw.S(" href=\"")
		_gsxgw.URL(string(_gsxv3))
		_gsxgw.S("\">Admin</a></nav></div></header>")
//line layout.gsx:60:4
		_gsxgw.S("<main id=\"content\" class=\"mx-auto max-w-3xl px-4 py-8\">")
//line layout.gsx:61:5
		_gsxgw.Node(ctx, children)
		_gsxgw.S("</main></body></html>")
		return _gsxgw.Err()
	})
}

// AdminShell wraps the authenticated admin app.

type AdminShellProps struct {
	Title    string
	Current  store.User
	Children gsx.Node
}

//line layout.gsx:68:1
func AdminShell(_gsxp AdminShellProps) gsx.Node {
	return gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
		title := _gsxp.Title
		current := _gsxp.Current
		children := _gsxp.Children
		_gsxgw := gsx.W(_gsxw)
		_gsxgw.S("<!DOCTYPE html>")
//line layout.gsx:70:2
		_gsxgw.S("<html lang=\"en\">")
//line layout.gsx:71:3
		_gsxgw.S("<head>")
//line layout.gsx:72:4
		_gsxgw.S("<meta charset=\"utf-8\"/>")
//line layout.gsx:73:4
		_gsxgw.S("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"/>")
//line layout.gsx:77:4
		_gsxgw.S("<title>Admin — ")
//line layout.gsx:77:21
		_gsxgw.Text(string(title))
		_gsxgw.S("</title>")
//line layout.gsx:78:4
		_gsxgw.S("<script src=\"https://cdn.tailwindcss.com\"></script>")
//line layout.gsx:79:4
		_gsxgw.S("<script src=\"https://unpkg.com/htmx.org@2.0.4\"></script></head>")
//line layout.gsx:81:3
		_gsxgw.S("<body class=\"bg-slate-100 text-slate-900\">")
//line layout.gsx:82:4
		_gsxgw.S("<header class=\"border-b bg-slate-900 text-slate-100\">")
//line layout.gsx:83:5
		_gsxgw.S("<div class=\"mx-auto flex max-w-5xl items-center justify-between px-4 py-3\">")
//line layout.gsx:86:6
		_gsxgw.S("<a class=\"flex items-center gap-2 text-lg font-semibold\"")
		_gsxv4, _gsxerr := _gsxf0.URLFor(ctx, (structpages.Ref("dashboard")))
		if _gsxerr != nil {
			return _gsxerr
		}
		_gsxgw.S(" href=\"")
		_gsxgw.URL(string(_gsxv4))
		_gsxgw.S("\">")
//line layout.gsx:90:7
		_gsxgw.S("<img src=\"/admin/static/admin-logo.svg\" alt=\"\" class=\"h-5 w-5\"/>blog admin</a>")
//line layout.gsx:97:6
		_gsxgw.S("<nav class=\"flex items-center gap-4 text-sm\">")
//line layout.gsx:98:7
		_gsxgw.S("<a class=\"hover:underline\"")
		_gsxv5, _gsxerr := _gsxf0.URLFor(ctx, (structpages.Ref("dashboard")))
		if _gsxerr != nil {
			return _gsxerr
		}
		_gsxgw.S(" href=\"")
		_gsxgw.URL(string(_gsxv5))
		_gsxgw.S("\">Dashboard</a>")
//line layout.gsx:104:7
		_gsxgw.S("<a class=\"hover:underline\"")
		_gsxv6, _gsxerr := _gsxf0.URLFor(ctx, (structpages.Ref("postList")))
		if _gsxerr != nil {
			return _gsxerr
		}
		_gsxgw.S(" href=\"")
		_gsxgw.URL(string(_gsxv6))
		_gsxgw.S("\">Posts</a>")
//line layout.gsx:110:7
		_gsxgw.S("<a class=\"hover:underline\"")
		_gsxv7, _gsxerr := _gsxf0.URLFor(ctx, (structpages.Ref("userList")))
		if _gsxerr != nil {
			return _gsxerr
		}
		_gsxgw.S(" href=\"")
		_gsxgw.URL(string(_gsxv7))
		_gsxgw.S("\">Users</a>")
//line layout.gsx:116:7
		_gsxgw.S("<span class=\"text-slate-400\">|</span>")
//line layout.gsx:117:7
		_gsxgw.S("<span class=\"text-slate-300\">")
//line layout.gsx:117:36
		_gsxgw.Text(string(current.Username))
		_gsxgw.S("</span>")
//line layout.gsx:118:7
		_gsxgw.S("<form method=\"POST\"")
		_gsxv8, _gsxerr := _gsxf0.URLFor(ctx, (structpages.Ref("logout")))
		if _gsxerr != nil {
			return _gsxerr
		}
		_gsxgw.S(" action=\"")
		_gsxgw.URL(string(_gsxv8))
		_gsxgw.S("\" class=\"m-0\">")
//line layout.gsx:123:8
		_gsxgw.S("<button class=\"text-slate-300 hover:text-white\" type=\"submit\">Sign out</button></form></nav></div></header>")
//line layout.gsx:133:4
		_gsxgw.S("<main id=\"content\" class=\"mx-auto max-w-5xl px-4 py-8\">")
//line layout.gsx:134:5
		_gsxgw.Node(ctx, children)
		_gsxgw.S("</main></body></html>")
		return _gsxgw.Err()
	})
}
